### ISSUE TITLE
Oblivion Quest Of The Week

### ISSUE THREAD

**Issue by pStyl3** [loot/oblivion#1339]
[Nexus](https://www.nexusmods.com/oblivion/mods/36336/)

Current masterlist data:
```yaml
  - name: 'QOTW( Season (One|Two|Three|Four)|0\d{2})\.esp'
    url:
      - link: 'https://www.nexusmods.com/oblivion/mods/36336/'
        name: 'Oblivion Quest Of The Week'
    msg: [ *alsoUseSilentVoice ]
  - name: 'QOTW Season (One|Two|Three|Four)\.esp'
    req: [ 'DLCShiveringIsles.esp' ]
  - name: 'QOTW0(0[1-9]|1\d|20)\.esp'
    msg:
      - <<: *alreadyInX
        subs: [ '**QOTW Season One.esp**' ]
        condition: 'active("QOTW Season One.esp")'
  - name: 'QOTW0(2[1-9]|3\d|40)\.esp'
    msg:
      - <<: *alreadyInX
        subs: [ '**QOTW Season Two.esp**' ]
        condition: 'active("QOTW Season Two.esp")'
  - name: 'QOTW0(4[1-9]|5\d|60)\.esp'
    msg:
      - <<: *alreadyInX
        subs: [ '**QOTW Season Three.esp**' ]
        condition: 'active("QOTW Season Three.esp")'
  - name: 'QOTW0(6[1-9]|7\d|80)\.esp'
    msg:
      - <<: *alreadyInX
        subs: [ '**QOTW Season Four.esp**' ]
        condition: 'active("QOTW Season Four.esp")'
  - name: 'QOTW Season One.esp'
    tag: [ Actors.ACBS ]
    dirty:
      - <<: *quickClean
        crc: 0x2926088F
        util: '[TES4Edit v4.0.4b](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 228
        udr: 2
  - name: 'QOTW Season Two.esp'
    tag:
      - Actors.AIPackages
      - C.Owner
      - Factions
    dirty:
      - <<: *quickClean
        crc: 0x112DCCE8
        util: '[TES4Edit v4.0.4b](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 133
  - name: 'QOTW Season Three.esp'
    tag:
      - Actors.AIPackages
      - Factions
    dirty:
      - <<: *quickClean
        crc: 0xF5D62DCC
        util: '[TES4Edit v4.0.4b](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 140
        udr: 1
  - name: 'QOTW Season Four.esp'
    tag:
      - Actors.ACBS
      - Actors.AIPackages
    dirty:
      - <<: *quickClean
        crc: 0xDDE504A7
        util: '[TES4Edit v4.0.4b](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 108
        udr: 5
  - name: 'QOTW021.esp'
    dirty:
      - <<: *quickClean
        crc: 0xD62553F4
        util: '[TES4Edit v4.0.4b](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 4
```

A whole lot of old versions have been archived on the mod page and the main file now only features `Quest Of The Week.esp`.

Changelog:
```
All QOTWs are now merged into one file
Fixed some bugs like the Water Ambushers issue
Quests with followers now have "Wait Here" and "Follow Me" dialogue options
Removed all unnecessary edits (QOTW mod is now fully cleaned) 
```

**Comment by MacSplody** [comment]
This is what I would do, the tag suggestions and requirements are probably the same, but should be double checked.
+ add the cleaning data.
```yaml
  - name: 'Quest Of The Week.esp'
    url:
      - link: 'https://www.nexusmods.com/oblivion/mods/36336/'
        name: 'Oblivion Quest Of The Week'
    req: [ 'DLCShiveringIsles.esp' ]
    msg: [ *alsoUseSilentVoice ]
    tag:
      - Actors.ACBS
      - Actors.AIPackages
      - Actors.Factions
      - C.Owner
  - name: 'QOTW( Season (One|Two|Three|Four)|0\d{2})\.esp'
    msg: [ *obsolete ]
```

As a side note `Actors.Factions` hasn't been added to the bash tag list, though it is used in several places.
