### ISSUE TITLE
300: Akaviri Stronghold

### ISSUE THREAD

**Issue by MacSplody** [loot/oblivion#150]
### [300: Akaviri Stronghold](https://www.nexusmods.com/oblivion/mods/3292)

**Cleaning info**
version 1.7

```yaml
  - name: '300_Akaviri_Stronghold.esp'
    dirty:
      - <<: *quickClean
        crc: 0x32741F48
        util: '[TES4Edit v4.0.3](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 18
        udr: 9
    clean:
      - crc: 0x142CB041
        util: 'TES4Edit v4.0.3'
```

**Compatibility**

![image](https://user-images.githubusercontent.com/1944639/80527233-f14c7280-898b-11ea-9bb4-ee80b6092bc0.png)

> Great Mod!! But this mod modifies OblivionGateToTamriel, so conflict with Ancient Tower mod by WilliamSea. 

[Ancient Towers](https://www.nexusmods.com/oblivion/mods/16308)

![image](https://user-images.githubusercontent.com/1944639/80527953-142b5680-898d-11ea-8794-2de12736339f.png)

- [x] Add Cleaning Info.
- [x] Add Ancient Towers to inc list.
