### ISSUE TITLE
Add a useBashTweakInstead for Vanity Camera Smoother once WB 312 is out

### ISSUE THREAD

**Issue by Infernio** [loot/oblivion#1856]
Wrye Bash 312 will include a new Bashed Patch tweak that can replicate the functionality of [Vanity Camera Smoother](https://www.nexusmods.com/oblivion/mods/1852).

**Comment by pStyl3** [comment]
@Infernio Since WB 312.1 is the current official version, can we add this message now?

```yaml
  - name: 'VanityCameraSmoother.esp'
    url:
      - link: 'https://www.nexusmods.com/oblivion/mods/1852/'
        name: 'Vanity Camera Smoother'
    msg:
      - <<: *useBashTweakInstead
        subs: [ 'Tweak Settings -> Level Difference: Creature Max [Unlimited]' ]
```

The content of `subs` has been copied from `Curseman''s Anti Extinction Mod.esp` from Oblivions masterlist, so we still need to change that.
