### ISSUE TITLE
Cleaning info for Greenview Manor

### ISSUE THREAD

**Issue by MacSplody** [loot/oblivion#186]
[Greenview Manor](https://www.nexusmods.com/oblivion/mods/37580)
Version 1.1

```yaml
  - name: 'Greenview Manor.esp'
    dirty:
      - <<: *quickClean
        crc: 0x205D6880
        util: '[TES4Edit v4.0.3](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 30
        udr: 56
```
