### ISSUE TITLE
A Nearly Human Spriggan warning/error

### ISSUE THREAD

**Issue by dancingmirrors** [loot/oblivion#1914]
Hello there,
(Warning, possible NSFW content below!)

The "A Nearly Human Spriggan" mod https://www.nexusmods.com/oblivion/mods/26251 issues a red warning in LOOT (I think it counts as an error), probably because it detects Oblivion Character Overhaul's ESP. Perhaps you could demote that from an error and mention instead something like "Make sure you have the OCOV2 Fix from the optional files".

I definitely haven't installed anything else that replaces the Spriggan, so I'm not sure exactly what is being detected.

Thanks!

**Comment by dancingmirrors** [comment]
After actually looking at the yaml file it doesn't seem to have anything to do with OCO at all.

```
  - name: 'Nude (Humanlike|Male) Spriggan( HGEC B| Tweaked)?\.esp'
    url:
      - link: 'https://www.nexusmods.com/oblivion/mods/26251/'
        name: 'A Nearly Human Spriggan'
    after: [ 'Knights.esp' ]
    inc:
      - 'Oblivion Sexualized Monsters.esm'
      - 'Oblivion Sexualized Monsters-exclu TRM.esm'
    msg:
      - <<: *useOnlyOneX
        subs: [ 'A Nearly Human Spriggan ESP' ]
        condition: 'file("Nude (Humanlike|Male) Spriggan( HGEC B| Tweaked)?\.esp")'
    tag: [ Graphics ]
  - name: 'Nude Humanlike Spriggan HGEC B.esp'
    msg:
      - <<: *requiresX
        type: say
        subs: [ '[HG EyeCandy Body](https://www.nexusmods.com/oblivion/mods/15802/)' ]
  - name: 'Nude Male Spriggan.esp'
```

I only have "Nude Humanlike Spriggan Tweaked.esp" and none of the others I see there.
