### ISSUE TITLE
Cleaning Report for Listener Overhaul

### ISSUE THREAD

**Issue by Sabre142** [loot/oblivion#206]
Mod name: Listener Overhaul

Nexus link: https://www.nexusmods.com/oblivion/mods/36002

Cleaning report:

```yaml
  - name: 'Listener Overhaul.esp'
    dirty:
      - <<: *quickClean
        crc: 0x95AFBF72
        util: '[TES4Edit v4.0.3b](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 3
        udr: 1
    clean:
      - crc: 0x7EB9C39F
        util: 'TES4Edit v4.0.3b'
```
