### ISSUE TITLE
Cleaning Report for World Maps For All Worldspaces

### ISSUE THREAD

**Issue by Sabre142** [loot/oblivion#210]
Mod name: World Maps For All Worldspaces

Nexus link: https://www.nexusmods.com/oblivion/mods/48914

Cleaning report:

```yaml
  - name: 'WorldMapsForAllWorldspaces.esp'
    dirty:
      - <<: *quickClean
        crc: 0x91E8C9C9
        util: '[TES4Edit v4.0.3b](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 171
    clean:
      - crc: 0x640D34C6
        util: 'TES4Edit v4.0.3b'
```

Load order notes from mod author: In order to avoid conflicts with other mods, you need to make sure that this mod is loaded AFTER mods that make changes within the involved worldspaces (adding player homes, moving things around, etc.), but BEFORE mods that change the world map of Cyrodiil (if those mods use any ESP files at all).
