### ISSUE TITLE
MigHorseArmor.esp incorrectly marked as dirty in masterlist

### ISSUE THREAD

**Issue by Sabre142** [loot/oblivion#213]
The mod [Universal Horse Armor](https://www.nexusmods.com/oblivion/mods/43037) is listed as dirty with 5 UDRs in the masterlist, when this isn't actually the case and it is completely clean.

```yaml
  - name: 'MigHorseArmor.esp'
    clean:
      - crc: 0x1C8F1C26
        util: 'TES4Edit v4.0.3b'
```
