### ISSUE TITLE
Oblivion Character Overhaul Patches

### ISSUE THREAD

**Issue by Dissident1337** [loot/oblivion#221]
Petitioning to add this to the LOOT recommendation messages whenever affected plugins are loaded in tandem with the [Oblivion Character Overhaul version 2](https://www.nexusmods.com/oblivion/mods/44676) (`Oblivion_Character_Overhaul.esp`):

- Horse Armor DLC
  - `DLCHorseArmor.esp`
- Mehrunes' Razor DLC
  - `DLCMehrunesRazor.esp`
- Orrery DLC
  - `DLCOrrery.esp`
- Thieves' Den DLC
  - `DLCThievesDen.esp`
- Knights of the Nine DLC
  - `Knights.esp`
- [Unofficial Oblivion Patch](https://www.nexusmods.com/oblivion/mods/5296) & [Shivering Isles Patch](https://www.nexusmods.com/oblivion/mods/10739)
  - `Unofficial Oblivion Patch.esp`
  - `Unofficial Shivering Isles Patch.esp`
- [Kvatch Rebuilt](https://www.nexusmods.com/oblivion/mods/15412)
  - `Kvatch Rebuilt.esp`

The recommendation would be to install the relevant plugin(s) from [Compatibility Patches for nuska's Oblivion Character Overhaul (v2)](https://www.nexusmods.com/oblivion/mods/46249) or [Oblivion Character Overhaul v2 - Unofficial Patch](https://www.nexusmods.com/oblivion/mods/48136).

**Comment by MacSplody** [comment]
[Oblivion Character Overhaul v2 - Unofficial Patch](https://www.nexusmods.com/oblivion/mods/48136) seems like the better option since It's more up to date.
But it does require all the DLC and unofficial patches.

The only way to tell the difference betweem the two files is CRC.
`Oblivion_Character_Overhaul.esp` **0x5B7D8F89** Original
`Oblivion_Character_Overhaul.esp` **0x5164E7AA** Unofficial Patch v1.2 

So maybe as an update patch message, and only show the nuska's OCO patch messages if the original file is present.

[Compatibility Patches for nuska's Oblivion Character Overhaul (v2)](https://www.nexusmods.com/oblivion/mods/46249)

`OCO_UOP_USIP_Patch.esp`
`OCO_DLCHorseArmor_Patch.esp`
`OCO_DLCOrrery_Patch.esp`
`OCO_DLCMehrunesRazor_Patch.esp`
`OCO_DLCThievesDen_Patch.esp`
`OCO_KnightsOTN_Patch.esp`

It might be easier to add the patch messages to the DLC files, instead of  `Oblivion_Character_Overhaul.esp`.

---

`OCO_KvatchRebuilt_Patch.esp` is already included in `Kvatch Rebuilt.esp` metadata.

```yaml
  - name: 'Kvatch Rebuilt.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/15412' ]
    msg:
      - <<: *patch3rdParty
        subs:
          - 'Oblivion Character Overhaul v2'
          - '[Compatibility Patches for nuska''s Oblivion Character Overhaul (v2)](https://www.nexusmods.com/oblivion/mods/46249)'
        condition: 'active("Oblivion_Character_Overhaul.esp") and not file("OCO_KvatchRebuilt_Patch.esp")'
```
