### ISSUE TITLE
Add tweak names to all instances of &useBashTweakInstead

### ISSUE THREAD

**Issue by sibir-ine** [loot/oblivion#249]
`&bashedPatchTweak` was replaced by `&useBashTweakInstead` in #248 as a part of #232.

It didn't allow for substituting the name of the tweaks in question, whereas `&useBashTweakInstead` does. As a result, there are now a lot of entries using `&useBashTweakInstead` without a specified tweak. These entries would obviously be improved by the addition of these tweaks.

This will require a bit of digging if it isn't stated on the plugin's mod page or obvious from the plugin's name. However, some tweaks are also helpfully named, such as "UOP Vampire Aging And Face Fix" for `UOP Vampire Aging & Face Fix.esp`.

There are currently **0** instances.

Done in d2bbd55

**Comment by MacSplody** [comment]
I'll switch this one to alsoUseX as it seems like the original file is required to use the tweak.

![image](https://user-images.githubusercontent.com/1944639/111020111-5d28a580-83bb-11eb-985f-229371cea8ca.png)

```yaml
  - name: 'VORB_no_mods.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/37013' ]
    msg: [ *useBashTweakInstead ]
```

**Comment by MacSplody** [comment]
I don't think there's actually a tweak for this one.
```yaml
  - name: 'Alchemist''s Tome.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/26104' ]
    msg: [ *useBashTweakInstead ]
```

But it does seem to do something similar to [Cobl Alchemical Catalogs](http://wryemusings.com/Cobl.html#AlchemicalCatalogs).
