### ISSUE TITLE
Black Ocean

### ISSUE THREAD

**Issue by sibir-ine** [loot/oblivion#299]
The entry for the mod [Black Ocean](https://www.nexusmods.com/oblivion/mods/22044) contains a message that links to what used to be the mod's main website, but, some time in 2014, it become someone else's current events blog.

The entry for reference
```yaml
  - name: 'Black ocean.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/22044' ]
    req: [ 'DLCShiveringIsles.esp' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: Knights of the Nine, unless using the patch available from [here](http://blackocean.ucoz.ru).'
          - lang: de
            text: 'Benötigt: Knights of the Nine, außer man nutzt den Patch der [hier](http://blackocean.ucoz.ru) verfügbar ist.'
    dirty:
      - crc: 0xab24aeb2
        <<: *dirtyPlugin
        itm: 273
        udr: 547
```

The mod is pretty ancient, so I'm not confident about finding the patch it's referring to. Also, the main mod is installed via executable, so I'm already hesitant to do anything with this mod that involves installing it i.e. recleaning. The only other place I could find the mod that may be legitimate (it's linked in the mod's UESP entry) is on a website called tesall(dot)ru, but it's entirely in Russian, which I don't speak. Can anyone else confirm whether the site & the mod's page on it is legitimate?

If not, considering that & the executable, I'd prefer to just remove the mod's entry outright. It's Nexus page has also been up for about 12 years & only has about 1000 downloads, so I don't think it's used enough for removing it to be an issue.
