### ISSUE TITLE
Reevaluate unaliased messages - Obsolete

### ISSUE THREAD

**Issue by pStyl3** [loot/oblivion#312]
[Main Issue](https://github.com/loot/oblivion/issues/311)

Please see the main issue for more information.

---
Possible message anchors that could be used to refactor these messages:

```yaml
  - &obsolete
    type: warn
    content:
      - lang: en
        text: 'Obsolete. Update to the latest version. %1%'
    subs: [ '' ]
  - &obsoleteUseFCOM
    <<: *obsolete
    subs: [ '[FCOM Convergence](https://www.nexusmods.com/oblivion/mods/12249)' ]
```

---

# Plugins reevaluated:
- [x] Addendum - Hungry.esp
- [x] Addendum - Sleepy.esp
- [x] Addendum - Thirsty.esp
- [x] Addendum - Tired.esp
- [x] Alternative Start v1.2.esp
- [x] BladeOfTheHaunted_UL_ImperialIsle_Patch.esp
- [x] Comprehensive Style Collection RM.esp
- [x] Cute Sexy Elves.esp
- [x] DarkUI Fix.esp
- [x] DS Alchemy Pouch.esp
- [x] EtInArkay-LushWoodlands patch.esp
- [x] FUQ Land.esp
- [x] kuerteeDeathHasPenalties.esp
- [x] LoversAdultPlay.esp
- [x] LoversAfterVoice.esp
- [x] LoversFOV.esp
- [x] LoversLoser.esp
- [x] LoversSpringSale.esp
- [x] LoversStopCombat.esp
- [x] LoversVoiceSound.esp
- [x] OldCrowInn-AncientRedwoods patch.esp
- [x] Ravenpride-Stendarr patch.esp
- [x] Sexual_Minotaur.esp
- [x] Sexual_Ogre.esp
- [x] Sexual_Spriggan.esp
- [x] SM_NoPoisonLevitationEffects.esp
- [x] VeronaHouseBloodlines-LushWoodlands fix.esp
- [x] VeronaHouseBloodlines-UL patches Merged.esp
- [x] WestRoads-RiverEthe patch.esp

---

# Done:
<details>
  <summary>Replaced messages</summary>

```yaml
  - name: 'VeronaHouseBloodlines-LushWoodlands fix.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Obsolete if using Lush Woodlands 1.3 or higher.'
          - lang: de
            text: 'Veraltet wenn Lush Woodlands 1.3 oder neuer genutzt wird.'

  - name: 'OldCrowInn-AncientRedwoods patch.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Obsolete if using Ancient Redwoods 1.6 or higher.'
          - lang: de
            text: 'Veraltet wenn Ancient Redwoods 1.6 oder neuer genutzt wird.'

  - name: 'WestRoads-RiverEthe patch.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Obselete - update to West Roads version 1.3+.'
          - lang: de
            text: 'Veraltet - Updaten Sie zu West Roads Version 1.3+.'

  - name: 'BladeOfTheHaunted_UL_ImperialIsle_Patch.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Obselete - update to version 2.2.1 of BladeOfTheHaunted.esp, then disable/remove this esp.'
          - lang: de
            text: 'Veraltet - Updaten Sie zu Version 2.2.1 von BladeOfTheHaunted.esp, dann deaktivieren/entfernen Sie diese esp.'

  - name: 'SM_NoPoisonLevitationEffects.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/12466' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Obsolete, you can update to Supreme Magicka 0.89b+ and set ''zzSMConfigurationQuest.bNoPoisonLevitationEffects'' to 1 in the ini for the same result.'
          - lang: de
            text: 'Veraltet, Sie können zu Supreme Magicka 0.89b+ updaten und ''zzSMConfigurationQuest.bNoPoisonLevitationEffects'' zu 1 setzen in der ini für das selbe Resultat.'

  - name: 'DarkUI Fix.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Old file. Not needed with DarkUI''d DarN 1.5.5 or newer.'
          - lang: de
            text: 'Alte Datei. Nicht benötigt mit DarkUI''d DarN 1.5.5 oder neuer.'

  - name: 'DS Alchemy Pouch.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Outdated. Upgrade to Portable Sorters.'
          - lang: de
            text: 'Veraltet. Upgraden Sie zu Portable Sorters.'

  - name: 'VeronaHouseBloodlines-UL patches Merged.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Outdated. Update the affected UL mods and then delete this patch.'
          - lang: de
            text: 'Veraltet. Updaten Sie die betroffenen UL Mods und löschen Sie dann diesen Patch.'

  - name: 'Ravenpride-Stendarr patch.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Obsolete as of version 1.2 of Stendarr Valley.'
          - lang: de
            text: 'Veraltet vom Stand der Version 1.2 aus von Stendarr Valley.'

  - name: 'Addendum - Tired.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Old, update to ''Tyler''s Hungry, Thirsty, Sleepy, Tired.esp''.'
          - lang: de
            text: 'Alt, Updaten Sie zu ''Tyler''s Hungry, Thirsty, Sleepy, Tired.esp''.'

  - name: 'Addendum - Hungry.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Old, update to ''Tyler''s Hungry, Thirsty, Sleepy, Tired.esp''.'
          - lang: de
            text: 'Alt, Updaten Sie zu ''Tyler''s Hungry, Thirsty, Sleepy, Tired.esp''.'

  - name: 'Addendum - Sleepy.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Old, update to ''Tyler''s Hungry, Thirsty, Sleepy, Tired.esp''.'
          - lang: de
            text: 'Alt, Updaten Sie zu ''Tyler''s Hungry, Thirsty, Sleepy, Tired.esp''.'

  - name: 'Addendum - Thirsty.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Old, update to ''Tyler''s Hungry, Thirsty, Sleepy, Tired.esp''.'
          - lang: de
            text: 'Alt, Updaten Sie zu ''Tyler''s Hungry, Thirsty, Sleepy, Tired.esp''.'

  - name: 'Comprehensive Style Collection RM.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Outdated. Update to latest version.'
          - lang: de
            text: 'Veraltet. Updaten Sie zur neuesten Version.'

  - name: 'Cute Sexy Elves.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Delete and update to newest version - ''Manga Elves.esp'''
          - lang: de
            text: 'Entfernen und Updaten Sie zur neuesten Version - ''Manga Elves.esp'''

  - name: 'kuerteeDeathHasPenalties.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/22121' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Obsolete. Upgrade to Kuertee''s "Alternatives To Death And Reload."'
          - lang: de
            text: 'Veraltet. Upgraden Sie zu Kuertee''s "Alternatives To Death And Reload."'

  - name: 'Sexual_Spriggan.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Obselete. Get Oblivion Sexualized Monsters.esm and OSM-All Genders.esp instead.'
          - lang: de
            text: 'Veraltet. Holen Sie sich stattdessen Oblivion Sexualized Monsters.esm und OSM-All Genders.esp.'

  - name: 'Sexual_Minotaur.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Obselete. Get Oblivion Sexualized Monsters.esm and OSM-All Genders.esp instead.'
          - lang: de
            text: 'Veraltet. Holen Sie sich stattdessen Oblivion Sexualized Monsters.esm und OSM-All Genders.esp.'

  - name: 'Sexual_Ogre.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Obselete. Get Oblivion Sexualized Monsters.esm and OSM-All Genders.esp instead.'
          - lang: de
            text: 'Veraltet. Holen Sie sich stattdessen Oblivion Sexualized Monsters.esm und OSM-All Genders.esp.'

  - name: 'EtInArkay-LushWoodlands patch.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Obsolete if using Lush Woodlands 1.3 or higher.'
          - lang: de
            text: 'Veraltet wenn Lush Woodlands 1.3 oder neuer genutzt wird.'

  - name: 'LoversAdultPlay.esp'
    inc: [ 'LoversSpringSale.esp' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Obsolete. Use LoversAdultPlayPlus.esp instead.'
          - lang: de
            text: 'Veraltet. Nutzen Sie stattdessen LoversAdultPlayPlus.esp.'

  - name: 'LoversSpringSale.esp'
    inc: [ 'LoversAdultPlay.esp' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Obsolete. Use LoversAdultPlayPlus.esp instead.'
          - lang: de
            text: 'Veraltet. Nutzen Sie stattdessen LoversAdultPlayPlus.esp.'

  - name: 'FUQ Land.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Old, update to LoversCharactors.esp'
          - lang: de
            text: 'Alt, Updaten Sie zu LoversCharactors.esp'

  - name: 'LoversFOV.esp'
    msg:
      - type: error
        content:
          - lang: en
            text: 'Delete. Use newer version of Lovers with PK. Integrated into 1.3.1 Rev38 and newer.'
          - lang: de
            text: 'Zu entfernen. Nutzen Sie neuere Version vom Lovers with PK. Integriert in 1.3.1 Rev38 oder neuer.'
        condition: *FCOMCond

  - name: 'LoversLoser.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Obsolete. Use LoversLandE.esp instead.'
          - lang: de
            text: 'Veraltet. Nutzen Sie stattdessen LoversLandE.esp.'

  - name: 'LoversVoiceSound.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Obsolete. Use Lovers with PK.esp instead.'
          - lang: de
            text: 'Veraltet. Nutzen Sie stattdessen Lovers with PK.esp.'

  - name: 'LoversAfterVoice.esp'
    msg:
      - type: error
        content:
          - lang: en
            text: 'Delete. Use newer version of Lovers with PK. Integrated into 1.3.1 Rev38 and newer.'
          - lang: de
            text: 'Zu entfernen. Nutzen Sie neuere Version vom Lovers with PK. Integriert in 1.3.1 Rev38 oder neuer.'
        condition: *FCOMCond

  - name: 'LoversStopCombat.esp'
    msg:
      - type: error
        content:
          - lang: en
            text: 'Delete. Use newer version of Lovers with PK. Integrated into 1.3.1 Rev38 and newer.'
          - lang: de
            text: 'Zu entfernen. Nutzen Sie neuere Version vom Lovers with PK. Integriert in 1.3.1 Rev38 oder neuer.'
        condition: *FCOMCond

  - name: 'Alternative Start v1.2.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Check to make sure you''re using v1.26 or later.'
          - lang: de
            text: 'Stellen Sie sicher das Sie v1.26 oder neuer nutzen.'
```

</details>

**Comment by sibir-ine** [comment]
Just a note for obsolete plugins: if the plugin is completely obsoleted, i.e., it should be uninstalled in favor of a different plugin, we should remove all it's other metadata besides location (e.g., `tag`s, cleaning data).

**Comment by pStyl3** [comment]
```yaml
  - name: 'kuerteeDeathHasPenalties.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/22121' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Obsolete. Upgrade to Kuertee''s "Alternatives To Death And Reload."'
          - lang: de
            text: 'Veraltet. Upgraden Sie zu Kuertee''s "Alternatives To Death And Reload."'
```
Can be replaced with:

```yaml
  - name: 'kuerteeDeathHasPenalties.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/22121' ]
    msg:
      - <<: *obsolete
        subs: [ '[Alternatives to death and reload](https://www.nexusmods.com/oblivion/mods/23862)' ]
```

**Comment by pStyl3** [comment]
```yaml
  - name: 'Cute Sexy Elves.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Delete and update to newest version - ''Manga Elves.esp'''
          - lang: de
            text: 'Entfernen und Updaten Sie zur neuesten Version - ''Manga Elves.esp'''
    tag:
      - Eyes
      - Graphics
      - Hair
      - NpcFaces
```
Can be replaced with:

```yaml
  - name: 'Cute Sexy Elves.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/34449' ]
    msg:
      - <<: *obsolete
        subs: [ '[Manga Elves](https://www.nexusmods.com/oblivion/mods/34449)' ]
```

**Comment by pStyl3** [comment]
**NSFW** warning for OSM

```yaml
  - name: 'Sexual_Spriggan.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Obselete. Get Oblivion Sexualized Monsters.esm and OSM-All Genders.esp instead.'
          - lang: de
            text: 'Veraltet. Holen Sie sich stattdessen Oblivion Sexualized Monsters.esm und OSM-All Genders.esp.'

  - name: 'Sexual_Minotaur.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Obselete. Get Oblivion Sexualized Monsters.esm and OSM-All Genders.esp instead.'
          - lang: de
            text: 'Veraltet. Holen Sie sich stattdessen Oblivion Sexualized Monsters.esm und OSM-All Genders.esp.'

  - name: 'Sexual_Ogre.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Obselete. Get Oblivion Sexualized Monsters.esm and OSM-All Genders.esp instead.'
          - lang: de
            text: 'Veraltet. Holen Sie sich stattdessen Oblivion Sexualized Monsters.esm und OSM-All Genders.esp.'
```

These messages (and thus the plugins) can be removed alltogether, as they seem to be unlocatable (a Google search suggests that `Sexual_Spriggan.esp` was around in 2009 or earlier).

**Comment by pStyl3** [comment]
```yaml
 - name: 'Addendum - Tired.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Old, update to ''Tyler''s Hungry, Thirsty, Sleepy, Tired.esp''.'
          - lang: de
            text: 'Alt, Updaten Sie zu ''Tyler''s Hungry, Thirsty, Sleepy, Tired.esp''.'

  - name: 'Addendum - Hungry.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Old, update to ''Tyler''s Hungry, Thirsty, Sleepy, Tired.esp''.'
          - lang: de
            text: 'Alt, Updaten Sie zu ''Tyler''s Hungry, Thirsty, Sleepy, Tired.esp''.'

  - name: 'Addendum - Sleepy.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Old, update to ''Tyler''s Hungry, Thirsty, Sleepy, Tired.esp''.'
          - lang: de
            text: 'Alt, Updaten Sie zu ''Tyler''s Hungry, Thirsty, Sleepy, Tired.esp''.'

  - name: 'Addendum - Thirsty.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Old, update to ''Tyler''s Hungry, Thirsty, Sleepy, Tired.esp''.'
          - lang: de
            text: 'Alt, Updaten Sie zu ''Tyler''s Hungry, Thirsty, Sleepy, Tired.esp''.'
```

These messages (and thus the plugins) can be removed alltogether, as they seem to be unlocatable. A Google search suggests that the plugins were around in 2008 and the recommended plugin `Tyler's Hungry, Thirsty, Sleepy, Tired.esp` was around in [2009](https://forums.nexusmods.com/index.php?/topic/140796-cant-change-eyes/). Removing these entries is the preferable way.

**Comment by pStyl3** [comment]
```yaml
  - name: 'Comprehensive Style Collection RM.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Outdated. Update to latest version.'
          - lang: de
            text: 'Veraltet. Updaten Sie zur neuesten Version.'
    tag:
      - Eyes
      - Hair
```

This message (and thus the plugin) can be removed. It is [gone](https://www.nexusmods.com/oblivion/mods/24077) from the Nexus, and while the latest version is uploaded on a private blog website, I don't trust the look of the website particularly (plus you need to wait 60s for the download, but the counter isn't counting down for me to begin with) and thus we will not link to it.

**Comment by pStyl3** [comment]
```yaml
  - name: 'Alternative Start v1.2.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Check to make sure you''re using v1.26 or later.'
          - lang: de
            text: 'Stellen Sie sicher das Sie v1.26 oder neuer nutzen.'
```
This entry can be removed, the plugin most likely was uploaded [here](https://www.nexusmods.com/oblivion/mods/11495). I think that this plugin name is the name for earlier versions of the mod, and sometime in 2007 or 2008 the plugin name was changed to `Alternative Start by Robert Evrae.esp`. The latter one is already featured in the masterlist, exactly above `Alternative Start v1.2.esp`, so there's no point in featuring this entry of a plugin that is long gone.

**Comment by pStyl3** [comment]
```yaml
LoversAdultPlay.esp
LoversSpringSale.esp
FUQ Land.esp
LoversFOV.esp
LoversLoser.esp
LoversVoiceSound.esp
LoversAfterVoice.esp
LoversStopCombat.esp
```
Those plugins will be removed alltogether. They are long gone, not to mention of concerning nature.

**Comment by pStyl3** [comment]
```yaml
  - name: 'WestRoads-RiverEthe patch.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Obselete - update to West Roads version 1.3+.'
          - lang: de
            text: 'Veraltet - Updaten Sie zu West Roads Version 1.3+.'
```
I've found West Roads [here](https://www.nexusmods.com/oblivion/mods/29523), but couldn't find `RiverEthe`, nor the patch for these two plugins. They seem long gone, so this plugin can be removed as well.

**Comment by pStyl3** [comment]
```yaml
  - name: 'VeronaHouseBloodlines-LushWoodlands fix.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Obsolete if using Lush Woodlands 1.3 or higher.'
          - lang: de
            text: 'Veraltet wenn Lush Woodlands 1.3 oder neuer genutzt wird.'
```
This entry can be replaced with:
```yaml
  - name: 'VeronaHouseBloodlines-LushWoodlands fix.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/14601' ]
    msg:
      - <<: *obsolete
        condition: 'file("xulLushWoodlands.esp")'
```
`xulLushWoodlands.esp` comes from [Unique Landscapes - The Great Forest - Lush Woodland](https://www.nexusmods.com/oblivion/mods/11164). Every file in the "old file" section is v1.3+, and the current main file is v2.0.1, so the condition should suffice.

```yaml
  - name: 'VeronaHouseBloodlines-UL patches Merged.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Outdated. Update the affected UL mods and then delete this patch.'
          - lang: de
            text: 'Veraltet. Updaten Sie die betroffenen UL Mods und löschen Sie dann diesen Patch.'
```
This plugins seems unlocatable, so it can be removed.

**Comment by pStyl3** [comment]
```yaml
  - name: 'SM_NoPoisonLevitationEffects.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/12466' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Obsolete, you can update to Supreme Magicka 0.89b+ and set ''zzSMConfigurationQuest.bNoPoisonLevitationEffects'' to 1 in the ini for the same result.'
          - lang: de
            text: 'Veraltet, Sie können zu Supreme Magicka 0.89b+ updaten und ''zzSMConfigurationQuest.bNoPoisonLevitationEffects'' zu 1 setzen in der ini für das selbe Resultat.'
```
Can be replaced with:
```yaml
  - name: 'SM_NoPoisonLevitationEffects.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/12466' ]
    msg: [ *obsolete ]
```

**Comment by pStyl3** [comment]
```yaml
  - name: 'DS Alchemy Pouch.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Outdated. Upgrade to Portable Sorters.'
          - lang: de
            text: 'Veraltet. Upgraden Sie zu Portable Sorters.'
```
This entry can be removed. I've found on the modpage of [Portable Sorters](https://www.nexusmods.com/oblivion/mods/25436) this explanation:
> Formerly Alchemy Pouch, Portable Sorters provides all the features of the previous mod plus sorters for potions and scrolls.

So this modpage is likely the place where the plugin was once uploaded to. Since it isn't provided anylonger, we can remove the plugin.

**Comment by pStyl3** [comment]
```yaml
  - name: 'DarkUI Fix.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Old file. Not needed with DarkUI''d DarN 1.5.5 or newer.'
          - lang: de
            text: 'Alte Datei. Nicht benötigt mit DarkUI''d DarN 1.5.5 oder neuer.'
```
This entry can be removed. On [DarkUId DarN](https://www.nexusmods.com/oblivion/mods/11280) the mod description reads:
> 1.4.5
> - Removed need for DarkUI Fix.esp. If you use it, you can now delete it and suffer no consequences. YAY!

Version 1.6 is the only available version and it was uploaded in 2009. No one will still use `DarkUI Fix.esp`.

**Comment by pStyl3** [comment]
```yaml

  - name: 'OldCrowInn-AncientRedwoods patch.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Obsolete if using Ancient Redwoods 1.6 or higher.'
          - lang: de
            text: 'Veraltet wenn Ancient Redwoods 1.6 oder neuer genutzt wird.'
```
I can't find this patch plugin anywhere. Version 1.6 of [Unique Landscapes - The Great Forest - Ancient Redwoods
](https://www.nexusmods.com/oblivion/mods/11163) (`xulAncientRedwoods.esp`) was uploaded in May 2009, current version is 2.0.1. This entry can therefore safely be removed.

**Comment by pStyl3** [comment]
```yaml
  - name: 'BladeOfTheHaunted_UL_ImperialIsle_Patch.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Obselete - update to version 2.2.1 of BladeOfTheHaunted.esp, then disable/remove this esp.'
          - lang: de
            text: 'Veraltet - Updaten Sie zu Version 2.2.1 von BladeOfTheHaunted.esp, dann deaktivieren/entfernen Sie diese esp.'
```

[The Blade of the Haunted - A Sword Quest](https://www.nexusmods.com/oblivion/mods/33089)

Version 2.2.1 of `BladeOfTheHaunted.esp` was uploaded in June 2011 and is itself long outdated. In 2013 the current version 3.1 was released.

It's safe to assume that `BladeOfTheHaunted_UL_ImperialIsle_Patch.esp` is no longer used by anyone and I also cannot find it anywhere, therefore remove this entry.
