### ISSUE TITLE
Reevaluate unaliased messages - Corrupt

### ISSUE THREAD

**Issue by pStyl3** [loot/oblivion#313]
[Main Issue](https://github.com/loot/oblivion/issues/311)

Please see the main issue for more information.

---
Possible message anchors that could be used to refactor these messages:

```yaml
  - &corrupt
    type: warn
    content:
      - lang: en
        text: 'This file is corrupt and should not be used.'
```

---

# Plugins reevaluated:
- [x] _Real_Lights.esp
- [x] DRSplatter.esp
- [x] moDem's City Life.esp
- [x] moDem's City Life - BP Compat.esp
- [x] Quest Award Leveller - Knights of the Nine.esp
- [x] TheForgottenRealm.esp
- [x] training spells.esp

---

# Done:
<details>
  <summary>Replaced messages</summary>

```yaml
  - name: 'moDem''s City Life - BP Compat.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/11278' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'May cause crashes in the IC Market district. May have been fixed. Needs verification.'
          - lang: de
            text: 'Kann Abstürze im IC Markt Abteil verursachen. Kann schon behoben sein. Braucht Überprüfung.'
      - type: say
        content:
          - lang: en
            text: 'For use with Better Cities use replacing fix for BBC.'
          - lang: de
            text: 'Für die Nutzung von Better Cities nutzen Sie replacing fix for BBC.'
        condition: 'file("Better Cities Resources.esm")'

  - name: 'moDem''s City Life.esp'
    url:
      - 'https://www.nexusmods.com/oblivion/mods/9450'
      - 'https://www.nexusmods.com/oblivion/mods/11351'
    msg:
      - type: say
        content:
          - lang: en
            text: 'May cause crashes in the IC Market district. May have been fixed. Needs verification.'
          - lang: de
            text: 'Kann Abstürze im IC Markt Abteil verursachen. Kann schon behoben sein. Braucht Überprüfung.'

  - name: 'Quest Award Leveller - Knights of the Nine.esp'
    tag: [ Scripts ]
    msg:
      - type: warn
        content:
          - lang: en
            text: 'Contains corrupt identical-to-master records. Automated cleaning with TES4Edit will remove them.'
          - lang: de
            text: 'Enthält korrupte Identisch-zum-Master Einträge. Automatische Säuberung mit TES4Edit wird diese entfernen.'
        condition: 'checksum("Quest Award Leveller - Knights of the Nine.esp", A80CD1A4)'

  - name: 'training spells.esp'
    msg:
      - type: error
        content:
          - lang: en
            text: 'DO NOT USE. This plugin is corrupt. It may be fixed by loading it in the CS and truncating the file when prompted.'
          - lang: de
            text: 'NICHT NUTZEN. Dieses Plugin ist korrupt. Es kann behoben werden durch Laden in der CS und die Datei zu kürzen wenn man gefragt wird.'
        condition: 'checksum("training spells.esp", DD4985A)'

  - name: 'DRSplatter.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/8273' ]
    req:
      - name: 'OBSE/Plugins/OBGEv2.dll'
        display: '[Oblivion Graphics Extender](https://www.nexusmods.com/oblivion/mods/30054)'
    msg:
      - type: warn
        content:
          - lang: en
            text: 'Remove this. Known to cause crashes and save game corruption.'
          - lang: de
            text: 'Entfernen Sie dies. Bekannt dafür Crashes und Spielstand-Korruption auszulösen.'

  - name: '_Real_Lights.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/10891' ]
    msg:
      - type: warn
        content:
          - lang: en
            text: 'Breaks the Umbacano branch of The Collector quest, and causes save game bloating.'
          - lang: de
            text: 'Bricht den Umbacano Zweig der The Collector Quest, und verursacht Spielstand-Aufblähungen.'
      - type: say
        content:
          - lang: en
            text: 'Recommended to use All Natural''s Real Lights implementation, as it doesn''t suffer from this, fixes a huge number of bugs in the original, and can be used on its own.'
          - lang: de
            text: 'Es wird empfohlen All Natural''s Real Lights Implementation zu nutzen, da dies nicht darunter leidet, behebt eine riesige Anzahl von Fehlern des Originals, und kann eigenständig genutzt werden.'

  - name: 'TheForgottenRealm.esp'
    url:
      - 'https://www.nexusmods.com/oblivion/mods/32559'
      - 'https://www.nexusmods.com/oblivion/mods/35696'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Possible CTDs. Enable only on time of game in TheForgottenRealm.esp'
          - lang: de
            text: 'Mögliche CTDs. On time of game nur aktivieren in TheForgottenRealm.esp'
```

</details>
