### ISSUE TITLE
Reevaluate unaliased messages - Wrye Bash

### ISSUE THREAD

**Issue by pStyl3** [loot/oblivion#314]
[Main Issue](https://github.com/loot/oblivion/issues/311)

Please see the main issue for more information.

---
Possible message anchors that could be used to refactor these messages:

```yaml
  - &useBashTweakInstead
    type: say
    content:
      - lang: en
        text: 'A Bashed Patch tweak can be used instead of this plugin. %1%'
    subs: [ '' ]
    condition: 'file("Bashed Patch.*\.esp")'
```

---

# Plugins reevaluated:
- [x] [Calsar] DontHideRings&Amulets_Clothing V1.0.esp
- [x] [Calsar] DontHideRings&Amulets_HA V1.0.esp
- [x] [Calsar] DontHideRings&Amulets_KOTN+SI V1.0.esp
- [x] [Natcalsar] DontHideRings&Amulets_Clothing V1.0.esp
- [x] [Natcalsar] DontHideRings&Amulets_HA V1.0.esp
- [x] [Natcalsar] DontHideRings&Amulets_KOTN+SI V1.0.esp
- [x] [Natcalsar] DontHideRings&Amulets_LA V1.0.esp
- [x] 300_Artifacts.esp
- [x] Adventurers_1.0.esp
- [x] BetterInns - Harvest Containers PATCH.esp
- [x] bgShaderStandAloneEV.esp
- [x] Castlevania.esp
- [x] Deepwood Adventures.esp
- [x] Dwemer_Rename.esp
- [x] Erics Crafting Mod.esp
- [x] Get_Your_Arrows_Back-9403.esp
- [x] Hemingweys Capes.esp
- [x] IC Atmospheric Shops Mod.esp
- [x] LostSpires_TheOrderofNibenay_patch.esp
- [x] More Lockpicks.esp
- [x] Near100PercentArrowRecovery.esp
- [x] Oblivifall - Losing My Religion Kvatch Rebuilt West Roads Patch.esp
- [x] Oblivifall - Losing My Religion West Roads Patch.esp
- [x] PMSneakySummonCompatibility.esp
- [x] real_tools.esp
- [x] RuinsofEvendallMod.esp
- [x] Rustle House - AN Patch.esp
- [x] WatersEdgeImproved.esp

---

# Done:
<details>
  <summary>Replaced messages</summary>

```yaml
  - name: 'Hemingweys Capes.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/29012' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Don''t use Wrye Bash''s Bashed Patch unlimited amulet''s tweak with this.'
          - lang: de
            text: 'Nutzen Sie nicht Wrye Bash''s Bashed Patch unlimited amulet''s Tweak hiermit.'
        condition: 'file("Bashed Patch.*\.esp")'
      - type: say
        content:
          - lang: en
            text: 'If you''re using this with the mod "Beast Characters lose tails no more", temporarily move it below the Bashed Patch whenever you rebuild it'
          - lang: de
            text: 'Wenn Sie dies nutzen mit der Mod "Beast Characters lose tails no more", verschieben Sie es temporär nach dem Bashed Patch immer wenn Sie es erneut-bauen'

  - name: 'WatersEdgeImproved.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/36896' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Needs Wrye Bash "Remove World Orphans" fix.'
          - lang: de
            text: 'Brauch Wrye Bash "Remove World Orphans" Fix.'

  - name: 'Get_Your_Arrows_Back-9403.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/9403' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Consider using Bash Patch tweaks instead, if possible.'
          - lang: de
            text: 'Erwägen Sie stattdessen den Bash Patch tweaks zu verwenden, wenn möglich.'

  - name: 'Rustle House - AN Patch.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/35252' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'It is possible when using All Natural + CBash the first floor of the house may become flooded. If so remove the "KhRHInterior" record from the Bashed Patch every time you rebuild. Or consider installing the "Rustle House CBash Fix.esp".'
          - lang: de
            text: 'Es ist möglich das wenn All Natural + CBash benutzt wird dass das Erdgeschoss des Hauses geflutet wird. Wenn dem so ist, entfernen Sie den "KhRHInterior" Eintrag von dem Bashed Patch jedes mal wenn sie neu-bauen. Oder erwägen Sie die Installation vom "Rustle House CBash Fix.esp".'

  - name: 'Erics Crafting Mod.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'If it doesn''t work move past your bashed patch (author recommends that placement but the tags added here should fix that... to be investigated)'
          - lang: de
            text: 'Wenn es nicht funktioniert, bewegen Sie es nach Ihrem Bashed Patch (Mod-Autor empfiehlt diese Platzierung aber die Tags die hier hinzugefügt wurden, sollten das beheben... muss noch untersucht werden)'

  - name: 'IC Atmospheric Shops Mod.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/27973' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'If not using WB you may have to move this above some item mods (thereby losing some changes from this) or lose some items from those mods.'
          - lang: de
            text: 'Wenn WB nicht genutzt, muss dieses womöglich vor anderen Gegenstände-Mods platziert werden (dadurch ein paar Änderungen davon verlierend) oder einige Gegenstände von diesen Mods verlieren.'

  - name: 'PMSneakySummonCompatibility.esp'
    group: *latePatchesGroup
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: Wrye Bash for proper use'
          - lang: de
            text: 'Benötigt: Wrye Bash für angemessene Nutzung'

  - name: 'real_tools.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Very dirty - Compile All Scripts was used on the mod. Either use CS or Tes4Edit to clean or use Wrye Bash''s Decompile All command.'
          - lang: de
            text: 'Sehr unsauber - Compile All Scripts wurde auf dieser Mod genutzt. Entweder nutzen Sie CS oder Tes4Edit zum Säubern oder Sie nutzen Wrye Bash''s Decompile All Befehl.'

  - name: 'Near100PercentArrowRecovery.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Consider using Bash Patch tweaks instead.'
          - lang: de
            text: 'Erwägen Sie stattdessen den Bash Patch tweaks zu nutzen.'

  - name: '[Natcalsar] DontHideRings&Amulets_LA V1.0.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'If possible use the Wrye Bash Bashed Patch tweak instead.'
          - lang: de
            text: 'Wenn möglich, nutzen Sie stattdessen den Wrye Bash Bashed Patch tweak.'

  - name: '[Natcalsar] DontHideRings&Amulets_HA V1.0.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'If possible use the Wrye Bash Bashed Patch tweak instead.'
          - lang: de
            text: 'Wenn möglich, nutzen Sie stattdessen den Wrye Bash Bashed Patch tweak.'

  - name: '[Natcalsar] DontHideRings&Amulets_Clothing V1.0.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'If possible use the Wrye Bash Bashed Patch tweak instead.'
          - lang: de
            text: 'Wenn möglich, nutzen Sie stattdessen den Wrye Bash Bashed Patch tweak.'

  - name: '[Natcalsar] DontHideRings&Amulets_KOTN+SI V1.0.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'If possible use the Wrye Bash Bashed Patch tweak instead.'
          - lang: de
            text: 'Wenn möglich, nutzen Sie stattdessen den Wrye Bash Bashed Patch tweak.'

  - name: '[Calsar] DontHideRings&Amulets_HA V1.0.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'If possible use the Wrye Bash Bashed Patch tweak instead.'
          - lang: de
            text: 'Wenn möglich, nutzen Sie stattdessen den Wrye Bash Bashed Patch tweak.'

  - name: '[Calsar] DontHideRings&Amulets_KOTN+SI V1.0.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'If possible use the Wrye Bash Bashed Patch tweak instead.'
          - lang: de
            text: 'Wenn möglich, nutzen Sie stattdessen den Wrye Bash Bashed Patch tweak.'

  - name: '[Calsar] DontHideRings&Amulets_Clothing V1.0.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'If possible use the Wrye Bash Bashed Patch tweak instead.'
          - lang: de
            text: 'Wenn möglich, nutzen Sie stattdessen den Wrye Bash Bashed Patch tweak.'

  - name: 'More Lockpicks.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'If using with an overhaul such as OOO (or many other mods), you really should use Wrye Bash or you''ll have loss of some leveled list changes.'
          - lang: de
            text: 'Wenn dies genutzt wird mit einer Überhol-Mod wie OOO (oder vielen anderen Mods) dann sollten Sie ersthaft Wyre Bash nutzen oder Sie verlieren Änderungen die an Leveled List gemacht wurden.'

  - name: 'Dwemer_Rename.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'If using Wrye Bash use the Bashed Patch Tweak instead and delete.'
          - lang: de
            text: 'Wenn Sie Wyre Bach nutzen, nutzen Sie stattdessen den Bashed Patch Tweak und löschen Sie es.'

  - name: 'Oblivifall - Losing My Religion West Roads Patch.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/31668' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Needs Wrye Bash''s "Remove World Orphans" fix.'
          - lang: de
            text: 'Brauch Wrye Bash''s "Remove World Orphans" Fix.'
        condition: 'checksum("Oblivifall - Losing My Religion West Roads Patch.esp",1B777711)'

  - name: 'Oblivifall - Losing My Religion Kvatch Rebuilt West Roads Patch.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/31668' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Needs Wrye Bash''s "Remove World Orphans" fix.'
          - lang: de
            text: 'Brauch Wrye Bash''s "Remove World Orphans" Fix.'
        condition: 'checksum("Oblivifall - Losing My Religion Kvatch Rebuilt West Roads Patch.esp",EDF95E8A)'

  - name: 'LostSpires_TheOrderofNibenay_patch.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/23657' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Needs Wrye Bash''s "Remove World Orphans" function run on it.'
          - lang: de
            text: 'Kann Ausführung von Wrye Bash''s "Remove World Orphans" Funktion darauf benötigen.'

  - name: 'BetterInns - Harvest Containers PATCH.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/29333' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'If using Harvest Containers v0.99.14, this plugin will need its master changed using Wrye Bash or TES4Gecko to reference the correct plugin, the addition of the Graphics and Scripts tags, e.g. {{BASH: Graphics, Scripts}}, and the removal of the Filter tag.'
          - lang: de
            text: 'Wenn Harvest Containers v0.99.14 genutzt, muss dieses Plugin den Master abgeändert werden mithilfe von Wrye Bash oder TES4Gecko um das korrekte Plugin zu referenzieren, das Hinzufügen von den Graphics und Scripts Tags, wie {{BASH: Graphics, Scripts}}, and die Entfernung des Filter Tags.'

  - name: 'RuinsofEvendallMod.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/25562' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Very dirty - Compile All Scripts was used on the mod. Either use CS or Tes4Edit to clean or use Wrye Bash''s Decompile All command.'
          - lang: de
            text: 'Sehr unsauber - Compile All Scripts wurde auf dieser Mod genutzt. Entweder nutzen Sie CS oder Tes4Edit zum Säubern oder Sie nutzen Wrye Bash''s Decompile All Befehl.'

  - name: 'Deepwood Adventures.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/38017' ]
    req: [ *SilentVoice ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Very dirty - Compile All Scripts was used on the mod. Either use CS or Tes4Edit to clean or use Wrye Bash''s Decompile All command.'
          - lang: de
            text: 'Sehr unsauber - Compile All Scripts wurde auf dieser Mod genutzt. Entweder nutzen Sie CS oder Tes4Edit zum Säubern oder Sie nutzen Wrye Bash''s Decompile All Befehl.'

  - name: 'Castlevania.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/39538' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'May require Wrye Bash''s "Remove World Orphans" function run on it.'
          - lang: de
            text: 'Kann Ausführung von Wrye Bash''s "Remove World Orphans" Funktion darauf benötigen.'

  - name: 'bgShaderStandAloneEV.esp'
    url:
      - 'http://theelderscrolls.info/?go=dlfile&fileid=336'
      - 'https://www.nexusmods.com/oblivion/mods/47189'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires Wrye Bash if using spell mods.'
          - lang: de
            text: 'Benötigt Wrye Bash wenn Zauberspruch Mods genutzt werden.'

  - name: 'Adventurers_1.0.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/4025' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Probably incompatible with every other overhaul out there - although with Wrye Bash *should* be able to be made to work with MMM.'
          - lang: de
            text: 'Wahrscheinlich inkompatibel mit jeder anderen Überhol-Mod die es gibt - obwohl Wrye Bash das fusionieren können *sollte* um mit MMM zu funktionieren.'

  - name: '300_Artifacts.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/2732' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'May require Wrye Bash''s "Remove World Orphans" function run on it.'
          - lang: de
            text: 'Kann Ausführung von Wrye Bash''s "Remove World Orphans" Funktion darauf benötigen.'
```

</details>

**Comment by sibir-ine** [comment]
I'll start working on these messages.

**Comment by sibir-ine** [comment]
```yaml
  - name: 'BetterInns - Harvest Containers PATCH.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/29333' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'If using Harvest Containers v0.99.14, this plugin will need its master changed using Wrye Bash or TES4Gecko to reference the correct plugin, the addition of the Graphics and Scripts tags, e.g. {{BASH: Graphics, Scripts}}, and the removal of the Filter tag.'
          - lang: de
            text: 'Wenn Harvest Containers v0.99.14 genutzt, muss dieses Plugin den Master abgeändert werden mithilfe von Wrye Bash oder TES4Gecko um das korrekte Plugin zu referenzieren, das Hinzufügen von den Graphics und Scripts Tags, wie {{BASH: Graphics, Scripts}}, and die Entfernung des Filter Tags.'
```

For this message, the tag suggestions aren't really necessary as the patch just edits records added by Better Inns, but I'll check the other patches to be sure in case there is a conflict (not sure what Filter tag it's referring to either, so that can be ignored). As for reassigning masters, I think there are three ways we can approach this:

1. We can generalize `*masterReassign` to be able to input any set of masters to be reassigned as opposed to just Oblivion & Nehrim (maybe we could flesh out the message by adding instructions or a link to a guide as well). I'm not sure about the process with xEdit (I'll need to test), but it can be done with WB simply, & it doesn't seem to cause any issues with the patch, so I'm not completely opposed to this option. Or,

2. We can replace the message with a `*patchUnavailable` message as the patch was designed for the older version of Harvest Containers, so a new patch for the new version would be preferred. Since master reassignment seems to be ill-advised in most cases, it might be for the best to just let the general user know that a patch specifically for the newer versions of HC isn't available. People who are more experienced with modding can probably handle reassigning the masters without causing more problems than the patch solves, or they could just make they're own patch, so I'm leaning more towards this option. However, since the mod is old & the author has explicitly stated it's EoSL, I could see the value in making an exception in this case. Or,

3. One of us could actually upload an updated patch as the authors of both mods have lax enough permissions for this purpose. We could also do one of the above & do this later, it was more just an afterthought. 🤷 @Infernio Maybe this could be a good opportunity to help you deal with the quarantine issue when you upload new WB executables. People seem to still be using both mods, so adding a patch message may help boost the new patch's visibility & get a decent amount of downloads. This is all assuming I didn't misunderstand both mods' permissions, of course.
