### ISSUE TITLE
Reevaluate unaliased messages - Version

### ISSUE THREAD

**Issue by pStyl3** [loot/oblivion#315]
[Main Issue](https://github.com/loot/oblivion/issues/311)

Please see the main issue for more information.

---
Possible message anchors that could be used to refactor these messages:

```yaml
  - &languageX
    type: say
    content:
      - lang: en
        text: 'Language: %1%'
      - lang: de
        text: 'Sprache: %1%'
      - lang: es
        text: 'Lengua: %1%'
      - lang: pt_BR
        text: 'Língua: %1%'
      - lang: pt_PT
        text: 'Língua: %1%'
  - &languageGerman
    <<: *languageX
    subs: [ '**de**' ]
```

---

# Plugins reevaluated:
- [x] AzurasServices_de.esp
- [x] Oblivion WarCry.esp
- [x] Q-Core - Icons.esp
- [x] Sexier Sheogorath DV.esp

---

# Done:
<details>
  <summary>Replaced messages</summary>

```yaml
  - name: 'Sexier Sheogorath DV.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'German version.'
          - lang: de
            text: 'Deutsche Version.'

  - name: 'Q-Core - Icons.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/19378' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'German version?'
          - lang: de
            text: 'Deutsche Version?'

  - name: 'AzurasServices_de.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/12187' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'German Version'
          - lang: de
            text: 'Deutsche Version'

  - name: 'Oblivion WarCry.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/45570' ]
    inc: [ 'FCOM_Convergence.esm' ]
    msg:
      # doNotClean
      - <<: *useInstead
        subs: [ '[Oblivion WarCry EV.esp](https://tesalliance.org/forums/index.php?/files/file/1294-fcom-convergence/)' ]
        condition: *FCOMCond
      - type: say
        content:
          - lang: en
            text: 'German version.'
          - lang: de
            text: 'Deutsche Version.'
```

</details>
