### ISSUE TITLE
Reevaluate unaliased messages - Rename

### ISSUE THREAD

**Issue by pStyl3** [loot/oblivion#316]
[Main Issue](https://github.com/loot/oblivion/issues/311)

Please see the main issue for more information.

---
Possible message anchors that could be used to refactor these messages:

```yaml
  - &renameFile
    type: say
    content:
      - lang: en
        text: 'Rename this file to %1%.'
```
```yaml
  - &renameXtoY
    type: warn
    content:
      - lang: en
        text: 'You need to rename %1% to %2% or this mod won''t work.'
```

---

# Plugins reevaluated:
- [x] EtInArkay-ColovianHighlands patch.esp
- [x] HTSCl_hud.esp

```yaml
Empty
```

---

# Done:
<details>
  <summary>Replaced messages</summary>

```yaml
  - name: 'HTSCl_hud.esp'
    url: [ 'https://www.loverslab.com/topic/171-htsclight-english/?ct=1568338462/' ]
    msg:
      - type: warn
        content:
          - lang: en
            text: 'You must rename "OBSE_Elys_Pluggy.dll" to "OBSE_Elys_Pluggy_Hud.dll"'
          - lang: de
            text: 'Sie müssen "OBSE_Elys_Pluggy.dll" in "OBSE_Elys_Pluggy_Hud.dll" umbenennen'
        condition: 'file("OBSE/Plugins/OBSE_Elys_Pluggy.dll") and not file("OBSE/Plugins/OBSE_Elys_Pluggy_Hud.dll")'
    req:
      - <<: *Pluggy
        condition: 'not file("OBSE/Plugins/OBSE_Elys_Pluggy_Hud.dll")'

  - name: 'EtInArkay-ColovianHighlands patch.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'If using ''xulColovianHighlands.esp'', it must be manually renamed to ''xulColovianHighlands_EV.esp'' for this patch to work.'
          - lang: de
            text: 'Wenn ''xulColovianHighlands.esp'' genutzt wird, muss es manuell zu ''xulColovianHighlands_EV.esp'' umbenannt werden damit der Patch funktioniert.'
        condition: 'file("xulColovianHighlands.esp")'
```

</details>

**Comment by MacSplody** [comment]
```yaml
  - name: 'EtInArkay-ColovianHighlands patch.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'If using ''xulColovianHighlands.esp'', it must be manually renamed to ''xulColovianHighlands_EV.esp'' for this patch to work.'
          - lang: de
            text: 'Wenn ''xulColovianHighlands.esp'' genutzt wird, muss es manuell zu ''xulColovianHighlands_EV.esp'' umbenannt werden damit der Patch funktioniert.'
        condition: 'file("xulColovianHighlands.esp")'
```

Wrye Bash master reassign might be a better approach in this case.

**Comment by MacSplody** [comment]
Removing `EtInArkay-ColovianHighlands patch.esp` in PR #425.

**Comment by MacSplody** [comment]
For HTSCl_hud.esp
There's metadata for `SimpleHUDClock.esp` that can be reused.

```yaml
  - name: 'SimpleHUDClock.esp'
    req:
      - <<: *Pluggy
        condition: 'not file("OBSE/Plugins/OBSE_Elys_Pluggy_Hud.dll")'
    msg:
      - <<: *renameXtoY
        subs:
          - 'OBSE_Elys_Pluggy.dll'
          - 'OBSE_Elys_Pluggy_Hud.dll'
        condition: 'file("OBSE/Plugins/OBSE_Elys_Pluggy.dll") and not file("OBSE/Plugins/OBSE_Elys_Pluggy_Hud.dll")'
```
