### ISSUE TITLE
Reevaluate unaliased messages - Incompatible

### ISSUE THREAD

**Issue by pStyl3** [loot/oblivion#318]
[Main Issue](https://github.com/loot/oblivion/issues/311)

Please see the main issue for more information.

---
Possible message anchors that could be used to refactor these messages:
```yaml
  - &compatIssuesWithX
    type: say
    content:
      - lang: en
        text: 'This plugin has compatibility issues with %1%. For more information, read this mod''s compatibility notes.'
```
```yaml
  - &compatNotes
    type: say
    content:
      - lang: en
        text: 'It is recommended that you read this mod''s [Compatibility Notes](%1%).'
```
```yaml
  - &requiresX
    type: warn
    content:
      - lang: en
        text: 'Requires: %1%'
  - &requiresBashedPatch
    <<: *requiresX
    type: error
    subs: [ '[Wrye Bash](https://www.nexusmods.com/oblivion/mods/22368) Bashed Patch' ]
    condition: 'not file("Bashed Patch.*\.esp")'
```
```yaml
  - &useOnlyOneX
    type: error
    content:
      - lang: en
        text: 'Use only one %1%.'
```

---

# Plugins reevaluated:
- [x] `.*(LODToggle).*\.esp`
- [x] `(CSV_Farms_(Better_Cities|Open_Cities|Open_Better_Cities)|CSVF_Road_Record_(BBC|OC|RB)(\+OC)?(\+RB)?)\.esp`
- [x] AHP.esp
- [x] Aspirias Fluch.esp
- [x] Ayleid Respawn v1.0 - For The Ayleid Steps.esp
- [x] Battle4Morrowind.esp
- [x] BEER! for Oblivion.esp
- [x] Clintmichs Beautiful Arcane University.esp
- [x] Clintmichs Beautiful Elven Gardens District v1.0.esp
- [x] Clintmichs Beautiful Elven Gardens District v1.1.esp
- [x] Clintmichs Beautiful Imperial City Arboretum.esp
- [x] Clintmichs Beautiful Imperial City Arboretum v1.1.esp
- [x] Clintmichs Beautiful Market District v1.3.esp
- [x] Clintmichs Beautiful Talos Plaza District.esp
- [x] Clintmichs Improved Prison District v1.1.esp
- [x] CreaturesFactionalised.esp
- [x] Curseman's Anti Extinction Mod.esp
- [x] Cybiades.esp
- [x] DremoraCompanion.esp
- [x] EnchantedGems_Geomancy.esp [Enchanting Gems](https://www.nexusmods.com/oblivion/mods/9569/)
- [x] geomancy.esp [Geomancy and Gem Dust](https://www.nexusmods.com/oblivion/mods/9580/)
- [x] FF_Real_Thirst.esp
- [x] HUDI.esp
- [x] JADDockTunnel.esp
- [x] kuerteeAutoSaveAndTime.esp
- [x] KS - Cities FPS Boost.esp [City FPS Boost](https://www.nexusmods.com/oblivion/mods/27727/)
- [x] KS - Imperial FPS Boost.esp [City FPS Boost](https://www.nexusmods.com/oblivion/mods/27727/)
- [x] KS - Kvatch FPS Boost.esp [City FPS Boost](https://www.nexusmods.com/oblivion/mods/27727/)
- [x] Locked Doors and Knocking v1.02.esp
- [x] Mart's Monster Mod - Slof Horses Complete.esp
- [x] M.O.E. - Bone Names and Priced Skull.esp
- [x] More Drinks.esp
- [x] mrSiikas_ImperialCathedral.esp
- [x] NoObsoleteEnemies.esp [No Obsolete Loot and Enemies](https://www.nexusmods.com/oblivion/mods/1952/)
- [x] NoObsoleteLoot.esp [No Obsolete Loot and Enemies](https://www.nexusmods.com/oblivion/mods/1952/)
- [x] NPC Static Level.esp
- [x] Oblivion Global Mod.esp **No Source Location**
- [x] OBSE-Storms & Sound( SI)?\.esp
- [x] QuietFeet.esp
- [x] RareItemsv1.18.esp [Rare Items](https://www.nexusmods.com/oblivion/mods/1968/)
- [x] RareItemsv1.18 for RCR.esp [Realistic Creature Rarity](https://www.nexusmods.com/oblivion/mods/2357/)
- [x] Realistic Creature Rarity.esp [Realistic Creature Rarity](https://www.nexusmods.com/oblivion/mods/2357/)
- [x] Region Revive - Lake Rumare.esp
- [x] Retros Fletching and Imbueing.esp
- [x] Robes Staves and Fists.esp
- [x] Slof's Better Bodies.esp
- [x] SM Security.esp
- [x] SPD-SailableRivers.esp [Speedy_s Sailable Rivers](https://www.nexusmods.com/oblivion/mods/31913/)
- [x] SPTDiverseGuards.esp
- [x] TamrielTravellersItemsUnscaled.esp
- [x] The Beautiful Market District.esp
- [x] Treasure Maps Blood Ransom.esp
- [x] Treasure Maps_Boethia's Burden.esp
- [x] Treasure Maps Meridias Womb.esp
- [x] Treasure Maps Revenge Of The Nords.esp
- [x] Treasure_Maps_The_Legend_Of_Jauffres_Gold.esp
- [x] TUR_GemDust.esp [Gem Dust](https://www.nexusmods.com/oblivion/mods/3566/)
- [x] varlatest.esp **No Source Location**
- [x] Walk to Oblivion.esp
- [x] WaterfrontMarket.esp
- [x] WaterfrontMarketNoShack.esp
- [x] XiaValentinesDayGift07.esp

```yaml
  - name: '.*(LODToggle).*\.esp'
    url:
      - link: 'https://www.nexusmods.com/oblivion/mods/37701'
        name: 'LOD Togglers for Mods'
    group: *lodGroup
    msg:
      - type: error
        content:
          - lang: en
            text: 'Remove this plugin from your load order after DistantLOD has been generated with [TES4LODGen](https://www.nexusmods.com/oblivion/mods/15781).'
          - lang: de
            text: 'Entfernen Sie dieses Plugin von Ihrer Ladereihenfolge nachdem DistantLOD generiert wurde mit [TES4LODGen](https://www.nexusmods.com/oblivion/mods/15781).'
      - type: warn
        content:
          - lang: en
            text: 'This plugin is outdated and may not be compatible with the latest version of the patched mod.'
          - lang: de
            text: 'Dieses Plugin ist veraltet und ist möglicherweise nicht kompatibel mit der aktuellen Version der gepatchten Mod.'

  - name: 'OBSE-Storms & Sound( SI)?\.esp'
    req: [ *OBSE ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'This one is compatible with all weather mods.'
          - lang: de
            text: 'Dieser ist kompatibel mit allen Wetter-Mods.'

  - name: '(CSV_Farms_(Better_Cities|Open_Cities|Open_Better_Cities)|CSVF_Road_Record_(BBC|OC|RB)(\+OC)?(\+RB)?)\.esp'
    msg:
      - type: warn
        content:
          - lang: en
            text: 'This patch is outdated and may not be compatible with the latest version of the patched mod.'
          - lang: de
            text: 'Dieser Patch ist veraltet und ist möglicherweise nicht kompatibel mit der aktuellen Version der gepatchten Mod.'

  - name: 'Mart''s Monster Mod - Slof Horses Complete.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires a Bashed Patch to be compatible with Slof''s Horses or Slof''s Extra Horses'
          - lang: de
            text: 'Benötigt einen Bashed Patch um kompatibel zu sein mit Slof''s Horses oder Slof''s Extra Horses'
        condition: 'file("Slof.*Horse.*\.esp")'

  - name: 'BEER! for Oblivion.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/8532' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Probably not compatible with OOO. Untested.'
          - lang: de
            text: 'Wahrscheinlich nicht kompatibel mit OOO. Ungetestet.'
        condition: *OOOCond

  - name: 'HUDI.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/34713' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Incompatible with: UI systems other than DarNified UI/Dark''d DarN/other DarN variants.'
          - lang: de
            text: 'Inkompatibel mit: UI Systemen außer DarNified UI/Dark''d DarN/andere DarN Varianten.'

  - name: 'More Drinks.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/5763' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Probably not compatible with OOO. Untested.'
          - lang: de
            text: 'Wahrscheinlich nicht kompatibel mit OOO. Ungetestet.'
        condition: *OOOCond

  - name: 'FF_Real_Thirst.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/14214/' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Incompatible with: Vampire mods.'
          - lang: de
            text: 'Inkompatibel mit: Vampir Mods.'

  - name: 'kuerteeAutoSaveAndTime.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/22136' ]
    inc:
      - 'Streamline 2.0.esp'
      - 'Streamline 2.1.esp'
      - 'Streamline 3.0.esp'
      - 'Streamline 3.1.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Incompatible with Cobl''s clock.'
          - lang: de
            text: 'Inkompatibel mit Cobl''s clock.'

  - name: 'XiaValentinesDayGift07.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/9111' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'May not be compatible with anything that modifies the Tiber Septim Hotel.'
          - lang: de
            text: 'Kann nicht kompatibel sein mit jeglichem was das Tiber Septim Hotel modifiziert.'

  - name: 'Robes Staves and Fists.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/26975' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Not compatible with any mod that uses "ModPCSpellEffectiveness".'
          - lang: de
            text: 'Nicht kompatibel mit jeder Mod die "ModPCSpellEffectiveness" nutzt.'
    req: [ *OBSE ]

  - name: 'TamrielTravellersItemsUnscaled.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/4387' ]
    inc: [ 'FCOM_Convergence.esm' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Not overhaul mod compatible.'
          - lang: de
            text: 'Nicht Überhol-Mod kompatibel.'

  - name: 'AHP.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/45513' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Incompatible with: TOTF.esp Disable on time of game. Enable only after AHP.esp quests have been completed'
          - lang: de
            text: 'Inkompatibel mit: TOTF.esp Deaktivieren Sie time of game. Nur Aktivieren nachdem AHP.esp Quests abgeschlossen wurden'
        condition: 'file("TOTF.esp")'
      - type: say
        content:
          - lang: en
            text: 'Incompatible with: See You Sleep. Disable on time of game. Enable only after AHP.esp quests have been completed'
          - lang: de
            text: 'Inkompatibel mit: See You Sleep. Deaktivieren Sie time of game. Nur Aktivieren nachdem AHP.esp Quests abgeschlossen wurden'

  - name: 'Battle4Morrowind.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/45467/' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Incompatible with: anything that changes Legion Armor.'
          - lang: de
            text: 'Inkompatibel mit: jeglichem das Legion Armor abändert.'

  - name: 'Clintmichs Beautiful Imperial City Arboretum.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/30114' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Probably incompatible with Better Cities IC Arboretum and similar.'
          - lang: de
            text: 'Wahrscheinlich inkompatibel mit Better Cities IC Arboretum und ähnlichem.'
        condition: 'file("Better Cities Resources.esm")'

  - name: 'Clintmichs Beautiful Imperial City Arboretum v1.1.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/30114' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Probably incompatible with Better Cities IC Arboretum and similar.'
          - lang: de
            text: 'Wahrscheinlich inkompatibel mit Better Cities IC Arboretum und ähnlichem.'
        condition: 'file("Better Cities Resources.esm")'

  - name: 'Clintmichs Beautiful Arcane University.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/30119' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Probably incompatible with Better Cities.'
          - lang: de
            text: 'Wahrscheinlich inkompatibel mit Better Cities.'
        condition: 'file("Better Cities Resources.esm")'

  - name: 'The Beautiful Market District.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/30012' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Probably incompatible with Better Cities.'
          - lang: de
            text: 'Wahrscheinlich inkompatibel mit Better Cities.'
        condition: 'file("Better Cities Resources.esm")'

  - name: 'Clintmichs Beautiful Market District v1.3.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/30012' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Probably incompatible with Better Cities.'
          - lang: de
            text: 'Wahrscheinlich inkompatibel mit Better Cities.'
        condition: 'file("Better Cities Resources.esm")'

  - name: 'Clintmichs Beautiful Elven Gardens District v1.1.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/30088' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Probably incompatible with Better Cities.'
          - lang: de
            text: 'Wahrscheinlich inkompatibel mit Better Cities.'
        condition: 'file("Better Cities Resources.esm")'

  - name: 'Clintmichs Improved Prison District v1.1.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/30136' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Probably incompatible with Better Cities.'
          - lang: de
            text: 'Wahrscheinlich inkompatibel mit Better Cities.'
        condition: 'file("Better Cities Resources.esm")'

  - name: 'Clintmichs Beautiful Talos Plaza District.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/30168' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Probably incompatible with Better Cities.'
          - lang: de
            text: 'Wahrscheinlich inkompatibel mit Better Cities.'
        condition: 'file("Better Cities Resources.esm")'

  - name: 'Locked Doors and Knocking v1.02.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/24218' ]
    inc: [ *BetterCities ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Incompatible with Better Cities, and probably other city altering mods.'
          - lang: de
            text: 'Inkompatibel mit Better Cities, und vermutlich anderen Städte-verändernden Mods.'

  - name: 'mrSiikas_ImperialCathedral.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/20555' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Incompatible with: Anything that modifies the Chorrol cathedral interior or exterior.'
          - lang: de
            text: 'Inkompatibel mit: Jeglichem das die das Äußere oder Innere der Chorrol Kathedrale modifiziert.'

  - name: 'Region Revive - Lake Rumare.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/22751' ]
    after:
      - 'TalosBridgeGateHouse.esp'
      - 'MTCExpandedVillages.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Incompatible with: most Weye-related mods.'
          - lang: de
            text: 'Inkompatibel mit: Meisten Weye-bezogenen Mods.'

  - name: 'Ayleid Respawn v1.0 - For The Ayleid Steps.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/24416' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'may be incompatible with AN/RL - to be confirmed.'
          - lang: de
            text: 'Kann inkompatibel mit AN/RL sein - muss noch nachgeforscht werden.'

  - name: 'QuietFeet.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/12331' ]
    msg:
      - *requiresBashedPatch
      - type: say
        content:
          - lang: en
            text: 'Recommended to upgrade to Quiet Feet MAX 2.0, which does not require a plugin and is more compatible.'
          - lang: de
            text: 'Empfohlen zu Quiet Feet MAX 2.0 upzugraden, welches kein Plugin voraussetzt und ist besser kompatibel.'
      - <<: *useBashTweakInstead
        subs: [ 'Tweak Actors -> Quiet Feet' ]

  - name: 'Cybiades.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/11755' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Do not use the (same name) compatible esp for UL:Lost; Update to the latest UL:Lost Coast.'
          - lang: de
            text: 'Nutzen Sie nicht den (selben Namen) kompatible esp für UL:Lost; Updaten Sie zur neuesten UL:Lost Coast.'

  - name: 'JADDockTunnel.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/4590' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Probably not compatible with Better Cities.'
          - lang: de
            text: 'Wahrscheinlich nicht kompatibel mit Better Cities.'
        condition: 'file("Better Cities Resources.esm")'

  - name: 'SPD-SailableRivers.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Most likely incompatible with some ULs'
          - lang: de
            text: 'Sehr wahrscheinlich inkompatibel mit einigen ULs'

  - name: 'KS - Cities FPS Boost.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Probably incompatible with Better Cities.'
          - lang: de
            text: 'Vermutlich inkompatibel mit Better Cities.'
        condition: 'file("Better Cities Resources.esm")'

  - name: 'KS - Imperial FPS Boost.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Probably incompatible with Better Cities.'
          - lang: de
            text: 'Vermutlich inkompatibel mit Better Cities.'
        condition: 'file("Better Cities Resources.esm")'

  - name: 'KS - Kvatch FPS Boost.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Probably incompatible with Better Cities.'
          - lang: de
            text: 'Vermutlich inkompatibel mit Better Cities.'
        condition: 'file("Better Cities Resources.esm")'

  - name: 'CreaturesFactionalised.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/36960' ]
    inc:
      - 'Mart''s Monster Mod.esm'
      - 'Oscuro''s_Oblivion_Overhaul.esm'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Incompatible with: Probably most overhauls if they touch creatures at all.'
          - lang: de
            text: 'Inkompatibel mit: Vermutlich meisten Überhol-Mods die irgendwie Kreaturen modifizieren.'

  - name: 'Curseman''s Anti Extinction Mod.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/21041/' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Incompatible with: Overhauls'
          - lang: de
            text: 'Inkompatibel mit: Überhol-Mods'

  - name: 'M.O.E. - Bone Names and Priced Skull.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/7902' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'May not be compatible with MMM bone loot - untested.'
          - lang: de
            text: 'Womöglich nicht kompatibel mit MMM bone loot - Ungetestet.'

  - name: 'NoObsoleteEnemies.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Highly likely to be incompatible with every overhaul out there.'
          - lang: de
            text: 'Höchst wahrscheinlich inkompatibel mit jeder verfügbaren Überhol-Mod.'

  - name: 'NoObsoleteLoot.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Highly likely to be incompatible with every overhaul out there.'
          - lang: de
            text: 'Höchst wahrscheinlich inkompatibel mit jeder verfügbaren Überhol-Mod.'

  - name: 'NPC Static Level.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/4905' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Almost certainly not compatible with Fran''s, MMM, OOO or FCOM.'
          - lang: de
            text: 'Sehr wahrscheinlich nicht kompatibel mit Fran''s, MMM, OOO oder FCOM.'

  - name: 'Realistic Creature Rarity.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Almost certainly not compatible with Fran''s, MMM, OOO or FCOM.'
          - lang: de
            text: 'Großer Wahrscheinlichkeit nicht kompatibel mit Fran''s, MMM, OOO oder FCOM.'

  - name: 'RareItemsv1.18.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Almost certainly not compatible with Fran''s, MMM, OOO or FCOM.'
          - lang: de
            text: 'Großer Wahrscheinlichkeit nicht kompatibel mit Fran''s, MMM, OOO oder FCOM.'

  - name: 'RareItemsv1.18 for RCR.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Almost certainly not compatible with Fran''s, MMM, OOO or FCOM.'
          - lang: de
            text: 'Großer Wahrscheinlichkeit nicht kompatibel mit Fran''s, MMM, OOO oder FCOM.'

  - name: 'SPTDiverseGuards.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/24614' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Probably not compatible with OOO. Update to version 2.0+.'
          - lang: de
            text: 'Wahrscheinlich nicht kompatibel mit OOO. Updaten Sie zur Version 2.0+.'
        condition: *OOOCond

  - name: 'EnchantedGems_Geomancy.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Similar to OOO and MMM Gems and Gem Dust - is almost certainly incompatible with those. Untested.'
          - lang: de
            text: 'Ähnlich zu OOO und MMM Gems und Gem Dust - ist sehr wahrscheinlich inkompatibel mit diesen. Ungetestet.'
    tag: [ Scripts ]

  - name: 'geomancy.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Similar to OOO and MMM Gems and Gem Dust - is almost certainly incompatible with those. Untested.'
          - lang: de
            text: 'Ähnlich zu OOO und MMM Gems und Gem Dust - ist sehr wahrscheinlich inkompatibel mit diesen. Ungetestet.'

  - name: 'TUR_GemDust.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Similar to OOO and MMM Gems and Gem Dust - is almost certainly incompatible with those. Untested.'
          - lang: de
            text: 'Ähnlich zu OOO und MMM Gems und Gem Dust - ist sehr wahrscheinlich inkompatibel mit diesen. Ungetestet.'
    tag: [ Scripts ]

  - name: 'varlatest.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Incompatible with: mods that alter Welkynd or Varla stones or the AyleidWell script.'
          - lang: de
            text: 'Inkompatibel mit: Mods die Welkynd oder Varla stones oder die AyleidWell Skripte abändern.'

  - name: 'SM Security.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/16136' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Partly included with OOO. May not be OOO compatible.'
          - lang: de
            text: 'Teilweise beinhaltet von OOO. Möglicherweise nicht kompatibel mit OOO.'
        condition: *OOOCond

  - name: 'Oblivion Global Mod.esp'
    msg:
      - type: warn
        content:
          - lang: en
            text: 'Incompatible with: Deadly Reflex'
          - lang: de
            text: 'Inkompatibel mit: Deadly Reflex'
        condition: 'file("Deadly Reflex.*\.esp")'

  - name: 'Slof''s Better Bodies.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/48904/' ]
    inc:
      - 'Cobl Races.esp'
      - 'Cobl Races - Balanced.esp'
      - 'Cobl Races TNR.esp'
      - 'Cobl Races TNR SI.esp'
    req:
      - name: 'MaleBodyReplacerV5.esp'
        display: '[Robert''s Male Body Replacer(v3, v4 or v5)](https://www.nexusmods.com/oblivion/mods/40532)'
      - name: 'RTFemaleReplacerV12.esp'
        display: '[Robert''s Female Body Replacer](https://www.nexusmods.com/oblivion/mods/15624)'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Incompatible with: Non-Robert''s body mods, Improved Facial Textures, Facial Textures by Enayla and Luchairs HGEC body seam reducer.'
          - lang: de
            text: 'Inkompatibel mit: Non-Robert''s body mods, Improved Facial Textures, Facial Textures by Enayla und Luchairs HGEC body seam reducer.'

  - name: 'Clintmichs Beautiful Elven Gardens District v1.0.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/30088' ]
    msg:
      - *obsolete
      - type: say
        content:
          - lang: en
            text: 'Probably incompatible with Better Cities.'
          - lang: de
            text: 'Wahrscheinlich inkompatibel mit Better Cities.'
        condition: 'file("Better Cities Resources.esm")'
```

---

# Done:
<details>
  <summary>Replaced messages</summary>

```yaml
  - name: 'Walk to Oblivion.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/23690/' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Incompatible with: Mods like Enhanced Daedric Invasion that modify Oblivion Gate scripts. Use Walk to Oblivion - OBSE.esp if you need compatibility with those mods.'
          - lang: de
            text: 'Inkompatibel mit: Mods wie Enhanced Daedric Invasion die Oblivion Gate Scripts modifizieren. Nutzen Sie Walk to Oblivion - OBSE.esp wenn sie Kompatibilität mit diesen Mods brauchen.'

  - name: 'DremoraCompanion.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'May be incompatible with plugins affecting sleep.'
          - lang: de
            text: 'Möglicherweise inkompatibel mit Plugins die Schlaf beeinflussen.'

  - name: 'Aspirias Fluch.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/30312' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Incompatible with: The Unique Landscapes mods.'
          - lang: de
            text: 'Inkompatibel mit: The Unique Landscapes Mods.'

  - name: 'Treasure_Maps_The_Legend_Of_Jauffres_Gold.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/11630' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Incompatible with: UL mod(s).'
          - lang: de
            text: 'Inkompatibel mit: UL Mod(s).'

  - name: 'Treasure Maps Revenge Of The Nords.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/11460' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Incompatible with: UL mod(s).'
          - lang: de
            text: 'Inkompatibel mit: UL Mod(s).'

  - name: 'Treasure Maps_Boethia''s Burden.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/16632' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Incompatible with: UL mod(s).'
          - lang: de
            text: 'Inkompatibel mit: UL Mod(s).'

  - name: 'Treasure Maps Meridias Womb.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/12251' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Incompatible with: UL mod(s).'
          - lang: de
            text: 'Inkompatibel mit: UL Mod(s).'

  - name: 'Treasure Maps Blood Ransom.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/11616' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Incompatible with: UL mod(s).'
          - lang: de
            text: 'Inkompatibel mit: UL Mod(s).'

  - name: 'Retros Fletching and Imbueing.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/2530' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'May not be compatible with MMM crafting - untested.'
          - lang: de
            text: 'Möglicherweise nicht kompatibel mit MMM Crafting - Ungetestet.'

  - name: 'WaterfrontMarket.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/22834' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Probably incompatible with Better Cities.'
          - lang: de
            text: 'Wahrscheinlich inkompatibel mit Better Cities.'
        condition: 'file("Better Cities Resources.esm")'

  - name: 'WaterfrontMarketNoShack.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/22834' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Probably incompatible with Better Cities.'
          - lang: de
            text: 'Wahrscheinlich inkompatibel mit Better Cities.'
        condition: 'file("Better Cities Resources.esm")'
```

</details>
