### ISSUE TITLE
Reevaluate unaliased messages - Requires

### ISSUE THREAD

**Issue by pStyl3** [loot/oblivion#319]
[Main Issue](https://github.com/loot/oblivion/issues/311)

Please see the main issue for more information.

---
Possible message anchors that could be used to refactor these messages:

```yaml
  - &requiresResources
    type: warn
    content:
      - lang: en
        text: 'Requires resources (e.g. meshes, textures; not plugins) from %1%.'
```
```yaml
  - &requiresX
    type: warn
    content:
      - lang: en
        text: 'Requires: %1%'
  - &requiresBashedPatch
    <<: *requiresX
    type: error
    subs: [ '[Wrye Bash](https://www.nexusmods.com/oblivion/mods/22368) Bashed Patch' ]
    condition: 'not file("Bashed Patch.*\.esp")'
```
---

# Plugins reevaluated:
- [x] BBBRoseoftheGuard.esp
- [x] BladeSong.esp
- [x] BrotherhoodRenewed - Oblivion XP Patch.esp
- [x] Chocolate Elves.esp
- [x] CM Alexander.esp
- [x] CMIsabell.esp
- [x] CompanionRepair.esp
- [x] DaggerfallResources02.esp
- [x] Diverse NPCs.esp
- [x] Dragon Templar.esp
- [x] Dremora Sigil Lords.esp
- [x] exhICMO.esp
- [x] FCOM_FighterGUnited.esp
- [x] FCOM_NewNPCClothes.esp
- [x] GGIlli.esp
- [x] HighrockVillage.esp
- [x] Katana Store.esp
- [x] LDPGC.esp
- [x] Legends - Zefaro Cottage.esp
- [x] Leviathan Trophy Soulgems.esp [Leviathan Trophy Soulgems](https://www.nexusmods.com/oblivion/mods/19862/)
- [x] LoversBorn.esp
- [x] LoversJoystick.esp
- [x] Lucha's Blood Witch.esp
- [x] Lucha's Blood Witcher.esp [Blood Witcher](https://www.nexusmods.com/oblivion/mods/39106)
- [x] MDMM.esp
- [x] Nude Humanlike Spriggan HGEC B.esp [A Nearly Human Spriggan](https://www.nexusmods.com/oblivion/mods/26251/)
- [x] Nude Male Spriggan.esp [A Nearly Human Spriggan](https://www.nexusmods.com/oblivion/mods/26251/)
- [x] pmAlchemyOverhaul.esp
- [x] Potion Of the Gods.esp
- [x] POTSB.esp
- [x] Rathunas01.esp
- [x] Ruins of Tarnesia.esp
- [x] TalosBridgeGateHouse.esp
- [x] TI-MM v04d.esp
- [x] TIE.esp
- [x] TGNDNessaStore.esp
- [x] ToaruMajutsunoOblivion.esp
- [x] TWMP_Azure_Palace.esp
- [x] VipCxj_AirSystem.esp
- [x] YakumoIsle.esp

```yaml
  - name: 'Katana Store.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/16424' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires patch to use with Kalikuts.'
          - lang: de
            text: 'Benötigt Patch um mit Kalikuts genutzt zu werden.'

  - name: 'VipCxj_AirSystem.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/36903/' ]
    req: [ *OBSEv20 ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: Coronerras Maximum Compatibility Skeletons, VipCxj''s Plugin Collection v3'
          - lang: de
            text: 'Benötigt: Coronerras Maximum Compatibility Skeletons, VipCxj''s Plugin Collection v3'

  - name: 'BBBRoseoftheGuard.esp'
    url:
      - 'https://www.nexusmods.com/oblivion/mods/34611'
      - 'https://www.nexusmods.com/oblivion/mods/43444'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires a Maximum Compatability Skeleton such as Coronnera''s.'
          - lang: de
            text: 'Benötigt ein Maximal Kompatibilität-Skelett wie zB Coronnera''s.'

  - name: 'LDPGC.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/45209' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: HGEC Body, Coronera''s Maximum Compatibility Skeleton'
          - lang: de
            text: 'Benötigt: HGEC Body, Coronera''s Maximum Compatibility Skeleton'

  - name: 'MDMM.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/45320' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: HGEC Body, Coronera''s Maximum Compatibility Skeleton'
          - lang: de
            text: 'Benötigt: HGEC Body, Coronera''s Maximum Compatibility Skeleton'

  - name: 'TGNDNessaStore.esp'
    url: [ 'https://www.loverslab.com/files/file/351-nessas-tgnd-stores' ]
    req:
      - *OBSEv20
      - *SilentVoice
      - name: 'TGND.esp'
        display: '[TGND Body Replacer](https://www.loverslab.com/files/file/253-tgnd-body-replacer/)'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: Skeleton nif replacer.'
          - lang: de
            text: 'Benötigt: Skeleton nif Ersetzer.'

  - name: 'BladeSong.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/49657' ]
    req: [ *OBSEv18 ]
    msg:
      - type: warn
        content:
          - lang: en
            text: 'Requires: Screen Effects.'
          - lang: de
            text: 'Benötigt: Screen Effects.'

  - name: 'BrotherhoodRenewed - Oblivion XP Patch.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/35333' ]
    req: [ *OBSE ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: Oblivion XP'
          - lang: de
            text: 'Benötigt: Oblivion XP'

  - name: 'DaggerfallResources02.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/38734' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: Tamriel Heightmaps, Tamriel Landscape Pack, Tamriel Resource Pack, Mr_Siikas Highrock Resources'
          - lang: de
            text: 'Benötigt: Tamriel Heightmaps, Tamriel Landscape Pack, Tamriel Resource Pack, Mr_Siikas Highrock Resources'

  - name: 'HighrockVillage.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/38734' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: Tamriel Heightmaps, Tamriel Landscape Pack, Tamriel Resource Pack, Mr_Siikas Highrock Resources'
          - lang: de
            text: 'Benötigt: Tamriel Heightmaps, Tamriel Landscape Pack, Tamriel Resource Pack, Mr_Siikas Highrock Resources'

  - name: 'Legends - Zefaro Cottage.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/35627' ]
    req: [ *OBSEv18 ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: USV, HGEC or Exnem body.'
          - lang: de
            text: 'Benötigt: USV, HGEC ode Exnem body.'

  - name: 'POTSB.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/42395' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: The original Path of the Skull Bearer mod''s files and requirements.'
          - lang: de
            text: 'Benötigt: Die original Path of the Skull Bearer mod''s Dateien und dessen Abhängigkeiten.'

  - name: 'Potion Of the Gods.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/23941/' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: Jojjo''s Lich King''s armour, shield, and Frostmourne sword. (<http://www.nexusmods.com/oblivion/mods/17032>)'
          - lang: de
            text: 'Benötigt: Jojjo''s Lich King''s armour, shield, und Frostmourne sword. (<http://www.nexusmods.com/oblivion/mods/17032>)'

  - name: 'ToaruMajutsunoOblivion.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/40264' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: Modular Beautiful People 2ch Edition Plus Plus'
          - lang: de
            text: 'Benötigt: Modular Beautiful People 2ch Edition Plus Plus'

  - name: 'YakumoIsle.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/37004' ]
    req: [ 'DLCShiveringIsles.esp' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: HGEC'
          - lang: de
            text: 'Benötigt: HGEC'

  - name: 'TWMP_Azure_Palace.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/36996' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: Tamriel Heightmaps'
          - lang: de
            text: 'Benötigt: Tamriel Heightmaps'

  - name: 'exhICMO.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: Better/Open Cities IC Market District Components.'
          - lang: de
            text: 'Benötigt: Better/Open Cities IC Market District Components.'

  - name: 'FCOM_NewNPCClothes.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/15165' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: ''New NPC Clothes 2.6''.'
          - lang: de
            text: 'Benötigt: ''New NPC Clothes 2.6''.'

  - name: 'Dremora Sigil Lords.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: Mod Daedric Lord Armor'
          - lang: de
            text: 'Benötigt: Mod Daedric Lord Armor'

  - name: 'Leviathan Trophy Soulgems.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: Tibixe''s String Function Collection and Leviathan Soulgems.'
          - lang: de
            text: 'Benötigt: Tibixe''s String Function Collection und Leviathan Soulgems.'

  - name: 'TI-MM v04d.esp'
    req: [ 'DLCShiveringIsles.esp' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: Qarl''s Harvest, Tamrielic Ingredients.'
          - lang: de
            text: 'Benötigt: Qarl''s Harvest, Tamrielic Ingredients.'

  - name: 'Nude Humanlike Spriggan HGEC B.esp'
    after: [ 'Knights - Unofficial Patch.esp' ]
    inc:
      - 'Oblivion Sexualized Monsters.esm'
      - 'Oblivion Sexualized Monsters-exclu TRM.esm'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: HGEC Body replacer'
          - lang: de
            text: 'Benötigt: HGEC Body replacer'
      - type: say
        content:
          - lang: en
            text: 'USE ONE ''nude * Spriggan.esp'' ONLY'
          - lang: de
            text: 'NUTZEN SIE NUR EINE ''nude * Spriggan.esp'''
        condition: 'file("Nude Humanlike Spriggan.esp") or file("Nude Humanlike Spriggan Tweaked.esp") or file("Nude Male Spriggan.esp")'

  - name: 'Nude Male Spriggan.esp'
    after: [ 'Knights - Unofficial Patch.esp' ]
    inc:
      - 'Oblivion Sexualized Monsters.esm'
      - 'Oblivion Sexualized Monsters-exclu TRM.esm'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: Robert Male Body v5'
          - lang: de
            text: 'Benötigt: Robert Male Body v5'
      - type: say
        content:
          - lang: en
            text: 'USE ONE ''nude * Spriggan.esp'' ONLY'
          - lang: de
            text: 'NUTZEN SIE NUR EINE ''nude * Spriggan.esp'''
        condition: 'file("Nude Humanlike Spriggan.esp") or file("Nude Humanlike Spriggan Tweaked.esp") or file("Nude Humanlike Spriggan HGEC B.esp")'

  - name: 'CompanionRepair.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/29263' ]
    req: [ *OBSE ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: RefStuff'
          - lang: de
            text: 'Benötigt: RefStuff'

  - name: 'Rathunas01.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/45880' ]
    req:
      - *OBSE
      - 'Cobl Main.esm'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: Unique Landscapes-Brena River Ravine'
          - lang: de
            text: 'Benötigt: Unique Landscapes-Brena River Ravine'

  - name: 'pmAlchemyOverhaul.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/41283' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: Real-time Interactions'
          - lang: de
            text: 'Benötigt: Real-time Interactions'

  - name: 'Lucha''s Blood Witcher.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: Robert''s Male v4 or v5'
          - lang: de
            text: 'Benötigt: Robert''s Male v4 oder v5'

  - name: 'Lucha''s Blood Witch.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: HG EyeCandy Body OR TeamFF Fantasy Figures OR Robert''s Female v12'
          - lang: de
            text: 'Benötigt: HG EyeCandy Body ODER TeamFF Fantasy Figures ODER Robert''s Female v12'

  - name: 'Chocolate Elves.esp'
    url:
      - 'https://www.nexusmods.com/oblivion/mods/18247'
      - 'https://www.nexusmods.com/oblivion/mods/24897'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: Hairs from Corean mod FULL 1.8'
          - lang: de
            text: 'Benötigt: Hairs from Corean mod FULL 1.8'

  - name: 'Diverse NPCs.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/14800' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: TNR, Ren''s Hair, Elaborate Eyes.'
          - lang: de
            text: 'Benötigt: TNR, Ren''s Hair, Elaborate Eyes.'

  - name: 'CM Alexander.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: Xenius'' Deus Obscura race'
          - lang: de
            text: 'Benötigt: Xenius'' Deus Obscura race'

  - name: 'CMIsabell.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/39206' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: CM Partners Basic'
          - lang: de
            text: 'Benötigt: CM Partners Basic'

  - name: 'GGIlli.esp'
    req: [ *OBSEv17 ]
    inc: [ 'Duke Patricks - Basic Combat Geometry.esp' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: Underdark: The Realm of Northdark.'
          - lang: de
            text: 'Benötigt: Underdark: The Realm of Northdark.'
```

---

# Done:
<details>
  <summary>Replaced messages</summary>

```yaml
  - name: 'FCOM_FighterGUnited.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/15519' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: Fighters Guild United.'
          - lang: de
            text: 'Benötigt: Fighters Guild United.'

  - name: 'LoversJoystick.esp'
    req: [ *OBSEv20 ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: LAPF v1.4, SetBody Blockhead 0.4'
          - lang: de
            text: 'Benötigt: LAPF v1.4, SetBody Blockhead 0.4'

  - name: 'LoversBorn.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: the meshes from ''DskRing'' mods, but not the ESPs.'
          - lang: de
            text: 'Benötigt: Die Meshes von ''DskRing'' Mods, aber nicht die ESPs.'

  - name: 'Dragon Templar.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/31961' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: Knights of the Nine'
          - lang: de
            text: 'Benötigt: Knights of the Nine'

  - name: 'Ruins of Tarnesia.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/6372' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Has a small landscape conflict with Unique Landcapes: Chorrol Hinterland.'
          - lang: de
            text: 'Hat einen kleinen Konflikt bezüglich Landschaften mit Unique Landcapes: Chorrol Hinterland.'
      - type: warn
        content:
          - lang: en
            text: 'Requires manual cleaning.'
          - lang: de
            text: 'Benötigt manuelle Säuberung.'

  - name: 'TalosBridgeGateHouse.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/37366' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires a patch if used with UL Imperial Isle.'
          - lang: de
            text: 'Benötigt einen Patch wenn es mit UL Imperial Isle genutzt wird.'

  - name: 'TIE.esp'
    inc: [ 'T.I.E4MODS.esp' ]
    tag:
      - Invent.Change
      - NPC.Class
      - Sound
      - SpellStats
      - Text
    msg:
      - type: say
        content:
          - lang: en
            text: 'Requires: compatibility mods to work with OOO, MMM, Fran''s or other large overhaul mods.'
          - lang: de
            text: 'Benötigt: Kompatibilitäts-Mods um zu funktionieren mit OOO, MMM, Fran''s oder anderen großen Überhol-Mods.'

```

</details>
