### ISSUE TITLE
Reevaluate unaliased messages - Update

### ISSUE THREAD

**Issue by pStyl3** [loot/oblivion#320]
[Main Issue](https://github.com/loot/oblivion/issues/311)

Please see the main issue for more information.

---
Possible message anchors that could be used to refactor these messages:
```yaml
  - &alreadyInOrFixedByX
    type: error
    content:
      - lang: en
        text: 'Delete. Already included or otherwise fixed in %1%.'
```
```yaml
  - &obsolete
    type: warn
    content:
      - lang: en
        text: 'Obsolete. Update to the latest version. %1%'
```
```yaml
  - &patchUpdateAvailable
    type: say
    content:
      - lang: en
        text: 'Update Patch available: %1%'
```
`&patchUpdateAvailable` is currently not featured in Oblivion's masterlist.

---

# Plugins reevaluated:
- [x] `Aliyah.esp`
- [x] `DABrinn.esp`
- [x] `DAClair.esp`
- [x] `DAEluna.esp`
- [x] `DAEva.esp`
- [x] `DAFeria.esp`
- [x] `DAIsrithr.esp`
- [x] `DAKaleahSuccubus.esp`
- [x] `DAMeridiaKatrina.esp`
- [x] `DANecsKarla.esp`
- [x] `DANECSSONNET.esp`
- [x] `DARaewyn.esp`
- [x] `DATiamsGirls.esp`
- [x] `DSoSMalamath.esp`
- [x] `Improved dungeons.esp`
- [x] `LostSpires-BravilBarrowfields patch.esp`
- [x] `Tamara.esp`
- [x] `WindspearTower-StendarrValley compatibility patch.esp`

```yaml
  - name: 'DSoSMalamath.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/36968' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Be sure to update to version 2.0. Version 1.x could break the Dark Brotherhood quest line.'
          - lang: de
            text: 'Stellen Sie sicher zu Version 2.0 zu updaten. Version 1.x kann die Dark Brotherhood Questreihe brechen.'

  - name: 'Improved dungeons.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/29378' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Update to latest version, called "The Lost Treasures Of Cyrodiil".'
          - lang: de
            text: 'Updaten Sie zur neuesten Version, genannt "The Lost Treasures Of Cyrodiil".'

  - name: 'WindspearTower-StendarrValley compatibility patch.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Update to patch version 1.1 if using Stendarr Valley 1.2'
          - lang: de
            text: 'Update Zum Patcher der Version 1.1 wenn Stendarr Valley 1.2 genutzt wird'

  - name: 'LostSpires-BravilBarrowfields patch.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Update to Bravil Barrowfields 1.3. Then deactivate this patch.'
          - lang: de
            text: 'Updaten Sie zu Bravil Barrowfields 1.3. Deaktivieren Sie dann diesen Patch.'

  - name: 'Nec-Character_Clair.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Consider updating to DACompilation_GO.esp/DACompilation_GO_APN.esp - this has some fixes and improvements and fixes game-destroying issues.'
          - lang: de
            text: 'Erwägen Sie zu DACompilation_GO.esp/DACompilation_GO_APN.esp upzudaten - Dies hat einige Fixes und Verbesserungen und behebt Spiel-zerstörende Probleme.'

  - name: 'DAEluna.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/13429' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Consider updating to DACompilation_GO.esp/DACompilation_GO_APN.esp - this has some fixes and improvements and fixes game-destroying issues.'
          - lang: de
            text: 'Erwägen Sie zu DACompilation_GO.esp/DACompilation_GO_APN.esp upzudaten - Dies hat einige Fixes und Verbesserungen und behebt Spiel-zerstörende Probleme.'

  - name: 'Tamara.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/12048' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Consider updating to DACompilation_GO.esp/DACompilation_GO_APN.esp - this has some fixes and improvements and fixes game-destroying issues.'
          - lang: de
            text: 'Erwägen Sie zu DACompilation_GO.esp/DACompilation_GO_APN.esp upzudaten - Dies hat einige Fixes und Verbesserungen und behebt Spiel-zerstörende Probleme.'

  - name: 'DABrinn.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/12245' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Consider updating to DACompilation_GO.esp/DACompilation_GO_APN.esp - this has some fixes and improvements and fixes game-destroying issues.'
          - lang: de
            text: 'Erwägen Sie zu DACompilation_GO.esp/DACompilation_GO_APN.esp upzudaten - Dies hat einige Fixes und Verbesserungen und behebt Spiel-zerstörende Probleme.'
    tag:
      - Eyes
      - Hair

  - name: 'DAEva.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/16807' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Consider updating to DACompilation_GO.esp/DACompilation_GO_APN.esp - this has some fixes and improvements and fixes game-destroying issues.'
          - lang: de
            text: 'Erwägen Sie zu DACompilation_GO.esp/DACompilation_GO_APN.esp upzudaten - Dies hat einige Fixes und Verbesserungen und behebt Spiel-zerstörende Probleme.'
    tag:
      - Eyes
      - Hair

  - name: 'DARaewyn.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/12134' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Consider updating to DACompilation_GO.esp/DACompilation_GO_APN.esp - this has some fixes and improvements and fixes game-destroying issues.'
          - lang: de
            text: 'Erwägen Sie zu DACompilation_GO.esp/DACompilation_GO_APN.esp upzudaten - Dies hat einige Fixes und Verbesserungen und behebt Spiel-zerstörende Probleme.'

  - name: 'DAFeria.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/15150' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Consider updating to DACompilation_GO.esp/DACompilation_GO_APN.esp - this has some fixes and improvements and fixes game-destroying issues.'
          - lang: de
            text: 'Erwägen Sie zu DACompilation_GO.esp/DACompilation_GO_APN.esp upzudaten - Dies hat einige Fixes und Verbesserungen und behebt Spiel-zerstörende Probleme.'

  - name: 'DAIsrithr.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/13894' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Consider updating to DACompilation_GO.esp/DACompilation_GO_APN.esp - this has some fixes and improvements and fixes game-destroying issues.'
          - lang: de
            text: 'Erwägen Sie zu DACompilation_GO.esp/DACompilation_GO_APN.esp upzudaten - Dies hat einige Fixes und Verbesserungen und behebt Spiel-zerstörende Probleme.'

  - name: 'DAKaleahSuccubus.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/13350' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Consider updating to DACompilation_GO.esp/DACompilation_GO_APN.esp - this has some fixes and improvements and fixes game-destroying issues.'
          - lang: de
            text: 'Erwägen Sie zu DACompilation_GO.esp/DACompilation_GO_APN.esp upzudaten - Dies hat einige Fixes und Verbesserungen und behebt Spiel-zerstörende Probleme.'

  - name: 'DAMeridiaKatrina.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Consider updating to DACompilation_GO.esp/DACompilation_GO_APN.esp - this has some fixes and improvements and fixes game-destroying issues.'
          - lang: de
            text: 'Erwägen Sie zu DACompilation_GO.esp/DACompilation_GO_APN.esp upzudaten - Dies hat einige Fixes und Verbesserungen und behebt Spiel-zerstörende Probleme.'
    tag:
      - Eyes
      - Hair

  - name: 'DANECSSONNET.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Consider updating to DACompilation_GO.esp/DACompilation_GO_APN.esp - this has some fixes and improvements and fixes game-destroying issues.'
          - lang: de
            text: 'Erwägen Sie zu DACompilation_GO.esp/DACompilation_GO_APN.esp upzudaten - Dies hat einige Fixes und Verbesserungen und behebt Spiel-zerstörende Probleme.'
    tag:
      - Eyes
      - Hair

  - name: 'DANecsKarla.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Consider updating to DACompilation_GO.esp/DACompilation_GO_APN.esp - this has some fixes and improvements and fixes game-destroying issues.'
          - lang: de
            text: 'Erwägen Sie zu DACompilation_GO.esp/DACompilation_GO_APN.esp upzudaten - Dies hat einige Fixes und Verbesserungen und behebt Spiel-zerstörende Probleme.'
    tag:
      - Eyes
      - Hair

  - name: 'DATiamsGirls.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Consider updating to DACompilation_GO.esp/DACompilation_GO_APN.esp - this has some fixes and improvements and fixes game-destroying issues.'
          - lang: de
            text: 'Erwägen Sie zu DACompilation_GO.esp/DACompilation_GO_APN.esp upzudaten - Dies hat einige Fixes und Verbesserungen und behebt Spiel-zerstörende Probleme.'
```

**Comment by MacSplody** [comment]
```yaml
  - name: 'Aliyah.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/12082' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Consider updating to DACompilation_GO.esp/DACompilation_GO_APN.esp - this has some fixes and improvements and fixes game-destroying issues.'
          - lang: de
            text: 'Erwägen Sie zu DACompilation_GO.esp/DACompilation_GO_APN.esp upzudaten - Dies hat einige Fixes und Verbesserungen und behebt Spiel-zerstörende Probleme.'
```

Replaced with:
```yaml
  - name: 'Aliyah.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/12082/' ]
    msg:
      - <<: *alreadyInX
        subs: [ '**DACompilation_GO ESPs**' ]
        condition: 'active("DACompilation_GO(_SI)?(_APN)?\.esp")'
      - <<: *useInstead
        type: say
        subs: [ '[Sclerocephalus CM Partner Compilation](https://www.nexusmods.com/oblivion/mods/33739/)' ]
        condition: 'not active("DACompilation_GO(_SI)?(_APN)?\.esp")'
```
