### ISSUE TITLE
Reevaluate unaliased messages - General

### ISSUE THREAD

**Issue by pStyl3** [loot/oblivion#321]
[Main Issue](https://github.com/loot/oblivion/issues/311)

Please see the main issue for more information.

---
Possible message anchors that could be used to refactor these messages:
```yaml
  - &compatIssuesWithX
    type: say
    content:
      - lang: en
        text: 'This plugin has compatibility issues with %1%. For more information, read this mod''s compatibility notes.'
```
`&compatIssuesWithX` is currently not featured within Oblivion's masterlist.

```yaml
  - &requiresResources
    type: warn
    content:
      - lang: en
        text: 'Requires resources (e.g. meshes, textures; not plugins) from %1%.'
```
```yaml
  - &patchUpdateAvailable
    type: say
    content:
      - lang: en
        text: 'Update Patch available: %1%'
```

---

# Plugins reevaluated:
- [x] (DC) County Sutch - New Haven.esp
- [x] (z)?Cats & Rats( for Francescos| for MMM)?\.esp
- [x] 1229-Priced Clutter-TESSource.esp
- [x] 300_Lore Dialogue.esp
- [x] AC's realistic priced clutter.esp
- [x] AdenseEpicDungeon.esp
- [x] Alchemy_Economy_Fix.esp
- [x] Alir'sArmor.esp
- [x] Angel's Arena Loot en.esp
- [x] Angel's Arena Loot rus.esp
- [x] Apachii_Goddess_Store.esp
- [x] Axebane_Hunters25.esp [Axebane Hunters 25 + Axebane RealHunger 25](https://www.nexusmods.com/oblivion/mods/6918/)
- [x] Ayleid Expansion.esp
- [x] Better_Gem_Pricing-7112.esp
- [x] Better Loot v1.0.esp
- [x] Bonemold_Helmet.esp
- [x] Book Placement v2.esp
- [x] Cheydinhal Petshop.esp
- [x] crimson dagger.esp
- [x] CompanionMaster.esp
- [x] Decorator Assistant.esp
- [x] Diseased Corpses.esp
- [x] Duke Patricks - Friendship Ring For Companion Detection.esp
- [x] FCOM_SpawnRatesStronger.esp
- [x] GuilesNameReplace-Scrolls.esp
- [x] Harvest [Flora].esp
- [x] Imperial City Miniature Model.esp
- [x] IWR-Lights.esp
- [x] IWR-Shutters.esp
- [x] IWR-Windows.esp
- [x] IWR - Windows Lights Shutters - Optimised.esp
- [x] Lycanthrope.esp
- [x] Lycanthrope 2.esp
- [x] Mage Equipment.esp
- [x] Mage Equipment - No Manni.esp
- [x] Mart's Monster Mod - Additional Enemy NPC Vars.esp
- [x] Mart's Monster Mod - More Passive Wildlife.esp
- [x] Miniature Necromancy Revised.esp
- [x] M.O.E. - Realistic Prices, Realistic Weights, No Quest Items.esp
- [x] M.O.E. - Vampire Clan Raelu.esp
- [x] Morrowind Ingredients_MMM.esp
- [x] mythsandlegends.esp
- [x] Natural_Vegetation_200%_by_Max_Tael.esp
- [x] Natural_Vegetation_by_Max_Tael.esp
- [x] Oblivion.esm
- [x] Oblivion Graphics Extender Support.esp
- [x] OotD_UL_Jerall_Patch.esp
- [x] PMSneakySummons-ForVanilla.esp
- [x] Poisoned Apple Fix.esp [Poisoned Apple Effect Fix](https://www.nexusmods.com/oblivion/mods/8073/)
- [x] Real Hunger, Cobl.esp
- [x] Region_Revive_-_Lake_Rumare_FuseSnailRacing_Patch.esp
- [x] Skill Perk Descriptions Enhancement.esp
- [x] S.P.A.M. 100+.esp
- [x] StarX Vanilla Vampires Revised.esp
- [x] TCP Silence remover.esp
- [x] TFE - Restore Cost.esp
- [x] TheStorytellersBrotherQuest.esp
- [x] TolawaylAyleidCity_Quest.esp
- [x] Trails Of Cyrodiil Merged UL Colovian Highlands.esp
- [x] UnnecessaryViolence.esp
- [x] VHBloodlines 1.2 Vwalk.esp
- [x] Vows and Covenants.esp

```yaml
  - name: 'Oblivion.esm'
    group: *gameMasterGroup
    msg:
      - type: error
        content:
          - lang: en
            text: 'This must not be activated. However, it can be useful when porting Oblivion mods to Nehrim.'
          - lang: de
            text: 'Dies darf nicht aktiviert werden. Dennoch, es kann nützlich sein beim Portieren von Oblivion Mods nach Nehrim.'
        condition: 'active("Oblivion.esm") and active("Nehrim.esm")'

  - name: 'Mart''s Monster Mod - Additional Enemy NPC Vars.esp'
    inc: [ 'FCOM_Convergence.esp' ]
    msg:
      # doNotClean
      - type: say
        content:
          - lang: en
            text: 'Can increase the chances of a CTD in a heavily modded game due to increased processor load.'
          - lang: de
            text: 'Kann Chancen für einen CTD erhöhen in stark gemoddeten Spielen aufgrund erhöhter Prozessor-Last.'

  - name: 'Mart''s Monster Mod - More Passive Wildlife.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Not recommended, has bugs.'
          - lang: de
            text: 'Nicht empfohlen, hat Fehler.'

  - name: 'FCOM_SpawnRatesStronger.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: '''Stronger'' is the same as ''Reduced'' but spawns will be more powerful.'
          - lang: de
            text: '''Stronger'' ist das gleiche wie ''Reduced'' aber Spawns werden mächtiger sein .'

  - name: 'IWR-Windows.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/6244' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Remember there are also the Retrofitted and Optimised IWR mods.'
          - lang: de
            text: 'Erinnerung das es auch die Retrogefitteten und optimierten IWR Mods gibt.'

  - name: 'IWR-Lights.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/6244' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Remember there are also the Retrofitted and Optimised IWR mods.'
          - lang: de
            text: 'Erinnerung das es auch die Retrogefitteten und optimierten IWR Mods gibt.'

  - name: 'IWR-Shutters.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/6244' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Remember there are also the Retrofitted and Optimised IWR mods.'
          - lang: de
            text: 'Erinnerung das es auch die Retrogefitteten und optimierten IWR Mods gibt.'

  - name: 'IWR - Windows Lights Shutters - Optimised.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/6244' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Needs original IWR files.'
          - lang: de
            text: 'Braucht originale IWR Dateien.'

  - name: '(z)?Cats & Rats( for Francescos| for MMM)?\.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Conflicts slightly with Harvest Containers; some in city containers will not play HC anims while this mod is active.'
          - lang: de
            text: 'Steht leicht im Konflikt mit Harvest Containers; Einige innerstädtische Behälter werden keine HC Animation abspielen während diese Mod aktiv ist.'

  - name: 'Alchemy_Economy_Fix.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/3413' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Not needed if using option in Enhanced Economy.'
          - lang: de
            text: 'Nicht benötigt wenn Option in Enhanced Economy genutzt wird.'

  - name: 'Duke Patricks - Friendship Ring For Companion Detection.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/21594' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Required if using any of Duke Patricks'' mods with companion mods.'
          - lang: de
            text: 'Benötigt wenn Sie irgendwelche von Duke Patricks'' Mods mit Begleiter Mods nutzen.'

  - name: 'Bonemold_Helmet.esp'
    url: [ 'http://www.nexusmods.com/oblivion/mods/6997' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Deactivate or delete this ESP file when using ''Unofficial Fran''s Armor'' (mesh and texture files are still required).'
          - lang: de
            text: 'Deaktivieren oder Entfernen Sie diese ESP Datei beim Benutzen von ''Unofficial Fran''s Armor'' (Mesh und Textur Dateien sind weiterhin benötigt).'

  - name: 'Alir''sArmor.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/35421' ]
    inc: [ 'Better Imperial City.esp' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'May conflict with mods that alter the exterior of the IC Market District.'
          - lang: de
            text: 'Kann im Konflikt mit Mods stehen die das Äußere des IC Markt Abteils abändern.'

  - name: 'crimson dagger.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/17043' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Due to a poorly written script the player will never recieve this weapon unless the mod is loaded second (right after Oblivion.esm)'
          - lang: de
            text: 'Durch ein dürftig geschriebenes Skript wird der Spieler niemals diese Waffe erhalten außer die Mod wird als zweites geladen (direkt nach Oblivion.esm)'
      - type: say
        content:
          - lang: en
            text: 'To aquire the weapon you must open the console and enter ''player.additem xx000ED3'' where xx is the hexadecimal mod index (LO number)'
          - lang: de
            text: 'Um diese Waffe zu erhalten müssen Sie die Konsole öffnen und ''player.additem xx000ED3'' eingeben wobei xx der hexadezimale Mod-Index ist (LO Nummer)'

  - name: 'Morrowind Ingredients_MMM.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/8394' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Consider Upgrading to Tamrielic Ingredients.'
          - lang: de
            text: 'Erwägen Sie zu Tamrielic Ingredients upzugraden.'

  - name: 'AdenseEpicDungeon.esp'
    url:
      - 'https://www.nexusmods.com/oblivion/mods/23170'
      - 'https://www.nexusmods.com/oblivion/mods/27520'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Newest version has the same name as the original. Check that you''re using at least v1.5.2.'
          - lang: de
            text: 'Neueste Version hat den selben Namen wie das Original. Überprüfen Sie das sie mindestens v1.5.2 nutzen.'

  - name: 'Cheydinhal Petshop.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/2054' ]
    msg:
      - type: warn
        content:
          - lang: en
            text: 'Has critical flaw affecting numerous mods. Remove immediately. Recommend replacing with Insanity''s Pet Shop for same functionality.'
          - lang: de
            text: 'Hat kritischen Fehler die zahlreiche Mods betrifft. Umgehend zu Löschen. Empfohlen durch Insanity''s Pet Shop zu ersetzen für die selbe Funktionalität.'

  - name: 'TCP Silence remover.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/17498' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Silenced character fix for The Contented Prisoner V 2.'
          - lang: de
            text: 'Stummer Charakter Fix für The Contented Prisoner V 2.'

  - name: '(DC) County Sutch - New Haven.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/32298' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'it replaces (DC) Sutch Reborn.esp'
          - lang: de
            text: 'Es ersetzt (DC) Sutch Reborn.esp'

  - name: 'Imperial City Miniature Model.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/4212' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'May conflict with many mods that alter the IC palace.'
          - lang: de
            text: 'Kann im Konflikt stehen mit vielen Mods die den IC Palast abändern.'

  - name: 'Lycanthrope.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/23599' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Consider upgrading to Werewolf - Legends of the North.'
          - lang: de
            text: 'Erwägen Sie zu Werewolf - Legends of the North upzugraden.'

  - name: 'Lycanthrope 2.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/23597' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Consider upgrading to Werewolf - Legends of the North.'
          - lang: de
            text: 'Erwägen Sie zu Werewolf - Legends of the North upzugraden.'

  - name: 'mythsandlegends.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/5902' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'May cause NPCs to generate the message "The ghosts mouth moves but you cannot hear what he says."'
          - lang: de
            text: 'Kann verursachen das NPCs die Nachricht generieren "The ghosts mouth moves but you cannot hear what he says."'

  - name: 'Region_Revive_-_Lake_Rumare_FuseSnailRacing_Patch.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/22751' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Patch for FuseSnailRacing.esp'
          - lang: de
            text: 'Patch für FuseSnailRacing.esp'
      - type: say
        content:
          - lang: en
            text: 'Loading this after OOO.esp causes OOO''s lockbash feature to fail. To fix this simply load RL-LR before OOO.esp.'
          - lang: de
            text: 'Wenn es nach OOO.esp geladen wird führt dies dazu das OOO''s Schloss-Einschlag Funktion fehlschlägt. Zum Beheben einfach RL-LR vor OOO.esp laden.'
        condition: *OOOCond

  - name: 'VHBloodlines 1.2 Vwalk.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/28223' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Mark Mergeable and deactivate - Merge animations does not seem to work properly for the original version of VH Bloodlines.'
          - lang: de
            text: 'Mit Mergeable(Zusammenführbar) markieren und deaktivieren - Animationen zusammenführen scheint nicht ordentlich zu funktionieren für die originale Version von VH Bloodlines.'
      - type: say
        content:
          - lang: en
            text: 'Sensual Walks for Arthmoor''s Verona House Bloodines SI Fixed contains bash tags to merge the animations, which work correctly on his version'
          - lang: de
            text: 'Sensual Walks for Arthmoor''s Verona House Bloodines SI Fixed enthält Bash Tags zum Zusammenführen der Animation, welche korrekt funktionieren mit dieser Version'

  - name: 'Angel''s Arena Loot en.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/14163' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Unlikely to work with other IC Arena mods'
          - lang: de
            text: 'Unwahrscheinlich zu funktionieren mit anderen IC Arena Mods'

  - name: 'Angel''s Arena Loot rus.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/14163' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Unlikely to work with other IC Arena mods'
          - lang: de
            text: 'Unwahrscheinlich zu funktionieren mit anderen IC Arena Mods'

  - name: 'Trails Of Cyrodiil Merged UL Colovian Highlands.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/44766' ]
    msg:
      - type: warn
        content:
          - lang: en
            text: 'Contains xulColovianHighlands.esp. ONLY load Meshes and Textures from UL Colovian Highlands when using this plugin.'
          - lang: de
            text: 'Beinhaltet xulColovianHighlands.esp. Laden Sie NUR Meshes und Texturen von UL Colovian Highlands wenn Sie dieses Plugin nutzen.'
        condition: 'file("xulColovianHighlands.esp")'

  - name: 'OotD_UL_Jerall_Patch.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/45611' ]
    msg:
      - type: warn
        content:
          - lang: en
            text: 'You do not need both of these patches! Disable OotD_UL_Jerall_Patch.esp.'
          - lang: de
            text: 'Sie brauchen nicht beide Patches! Deaktivieren Sie OotD_UL_Jerall_Patch.esp.'
        condition: 'file("OrdenDesDrachen-JerallGlacier patch.esp")'

  - name: 'Diseased Corpses.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/9758' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'If using HC decide which you want to have priority and move that one after the other (needs compatibility patch that is not currently available)'
          - lang: de
            text: 'Wenn HC genutzt wird, entscheiden Sie welcher für Sie Priorität hat und verschieben Sie diesen vor dem anderen (braucht Kompatibilitäts-Patch der momentan nicht verfügbar ist)'

  - name: '1229-Priced Clutter-TESSource.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'May not work with Living Economy as LE scripts tend to overwrite pricing mods.'
          - lang: de
            text: 'Funktioniert womöglich nicht mit Living Economy da LE Skripte dazu tendieren Preisgestaltungs-Mods zu überschreiben.'
        condition: 'file("Living Economy.*\.esp")'

  - name: 'AC''s realistic priced clutter.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'May not work with Living Economy as LE scripts tend to overwrite pricing mods.'
          - lang: de
            text: 'Funktioniert womöglich nicht mit Living Economy da LE Skripte dazu tendieren Preisgestaltungs-Mods zu überschreiben.'
        condition: 'file("Living Economy.*\.esp")'

  - name: 'Better_Gem_Pricing-7112.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/7112' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'May not work with Living Economy as LE scripts tend to overwrite pricing mods.'
          - lang: de
            text: 'Funktioniert womöglich nicht mit Living Economy da LE Skripte dazu tendieren Preisgestaltungs-Mods zu überschreiben.'
        condition: 'file("Living Economy.*\.esp")'

  - name: 'Book Placement v2.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/6262' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Try AutoBookPlacer v3 or later.'
          - lang: de
            text: 'Versuchen Sie AutoBookPlacer v3 oder neuer.'

  - name: 'Axebane_Hunters25.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'May break MMM Hunting and Crafting. Not fully tested.'
          - lang: de
            text: 'Bricht vielleicht MMM Hunting and Crafting. Nicht vollständig getestet.'
        condition: 'file("Mart''s Monster Mod - Hunting & Crafting.esp")'

  - name: 'Better Loot v1.0.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Will totally FUBAR OOO''s item scaling.'
          - lang: de
            text: 'Wird totale Zerstörung für OOO''s Skalierung der Gegenstände bedeuten.'
        condition: *OOOCond

  - name: 'Decorator Assistant.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Check if the version is 1.1 or later.'
          - lang: de
            text: 'Überprüfen Sie ob die Version 1.1 oder neuer ist.'

  - name: 'GuilesNameReplace-Scrolls.esp'
    tag: [ Names ]
  - name: 'haz_ct_REMOVE.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'ONLY Activate this if you want to remove the changes made by the Classic Travel mod components ct4 & ct1.'
          - lang: de
            text: 'NUR aktivieren wenn Sie möchten dass die Änderungen von Classic Travel mod components ct4 & ct1 rückgängig gemacht werden.'

  - name: 'M.O.E. - Realistic Prices, Realistic Weights, No Quest Items.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/7902' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'May cause unexpected results with Living Economy, Fran''s, OOO, MMM and/or FCOM.'
          - lang: de
            text: 'Kann zu unerwarteten Folgen führen mit Living Economy, Fran''s, OOO, MMM und/oder FCOM.'
      - type: say
        content:
          - lang: en
            text: 'May cause some quest items to revert to vanilla stats when using overhaul mods. Will not remove quest status from non-vanilla quests.'
          - lang: de
            text: 'Kann dazu führen das einige Quest-Gegenstände zurück zu Ihren ursprünglichen Eigenschaften zurückkehren. Wird nicht den Quest-Status von nicht-originalen Quests entfernen.'

  - name: 'Skill Perk Descriptions Enhancement.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Conflicts with OOO''s changes to skill perks and their descriptions.'
          - lang: de
            text: 'Steht im Konflikt mit OOO''s Änderungen an den Fähigkeits-Perks und deren Beschreibungen.'
        condition: *OOOCond

  - name: 'M.O.E. - Vampire Clan Raelu.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/7902' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'May have problems with OOO.'
          - lang: de
            text: 'Kann Probleme mit OOO haben.'
        condition: *OOOCond

  - name: 'Miniature Necromancy Revised.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/47903' ]
    msg:
      - type: warn
        content:
          - lang: en
            text: 'Do not have Jpm''s original active at the same time as this.'
          - lang: de
            text: 'Haben Sie nicht Jpm''s original aktiv zur selben Zeit wie dies.'
        condition: 'file("Jpm''s Miniature Necromancy.esp") or file("Jpm''s Miniature Necromancy RUS.esp")'

  - name: 'TFE - Restore Cost.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Not needed if using LAME.'
          - lang: de
            text: 'Nicht nötig wenn LAME genutzt wird.'

  - name: 'PMSneakySummons-ForVanilla.esp'
    inc: [ 'PMSneakySummonCompatibility.esp' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'To have magic overhaul features move before magic overhauls (but then you won''t get the features of this)'
          - lang: de
            text: 'Um Magie-Überhol Funktionalitäten zu haben, bewegen Sie es vor Magie-Überhol-Mods (aber dann bekommen Sie nicht die Funktionalitäten hiervon)'
  - name: 'Poisoned Apple Fix.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Will probably break Dark Botherhood guild quest.'
          - lang: de
            text: 'Wird wahrscheinlich die Dark Botherhood Gilden Quest brechen.'

  - name: 'S.P.A.M. 100+.esp'
    req:
      - name: 'OBSE/Plugins/OBSE_Elys_Uncapper.dll'
        display: '[Oblivion -Elys- Uncapper](https://www.nexusmods.com/oblivion/mods/13841) or [Legendary Mastery](https://www.nexusmods.com/oblivion/mods/3664)'
        condition: 'not file("Toaster''s Legendary Mastery.esp")'
    msg:
      - type: say
        content:
          - lang: en
            text: 'All character attributes MUST be below 95 if adding one of those uncapper mods and this SPAM plugin.'
          - lang: de
            text: 'Alle Charakter Attribute MÜSSEN unter 95 sein wenn Sie einer der Uncapper-Mods und dieses SPAM Plugin hinzufügen.'

  - name: 'Real Hunger, Cobl.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/21106' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Realistic hunger mods and vampire mods may conflict seriously.'
          - lang: de
            text: 'Realistische Hunger-Mods und Vampir-Mods können ernsthaft im Konflikt stehen.'

  - name: 'Oblivion Graphics Extender Support.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/30054' ]
    msg:
      - *masterReassign
      - type: warn
        content:
          - lang: en
            text: 'The support plugin does not work. Shaders must be loaded using the shaderlist.'
          - lang: de
            text: 'Das Support Plugin funktioniert nicht. Shader müssen mit der Shaderlist geladen werden.'
        condition: *nehrimCond

  - name: 'CompanionMaster.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/29652' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Some menu functions may not work.'
          - lang: de
            text: 'Einige Menü Funktionen könnten nicht funktionieren.'
        condition: *nehrimCond
```

---

# Done:
<details>
  <summary>Replaced messages</summary>

```yaml
  - name: '300_Lore Dialogue.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/9722' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'May have a problem with Storms and Sounds.'
          - lang: de
            text: 'Kann ein Problem mit Storms and Sounds haben.'

  - name: 'Ayleid Expansion.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Suspected of messing up your magicka multiplier.'
          - lang: de
            text: 'Verdächtigt Ihren Magicka Multiplikator zu vermasseln.'

  - name: 'Harvest [Flora].esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/2037' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Make sure you have v3.0.1 or later, which removes a CTD bug with the Harrada root.'
          - lang: de
            text: 'Stellen Sie sicher das Sie v3.0.1 oder neuer haben, welcher ein CTD Bug mit der Harrada Wurzel entfernt.'
    tag:
      - Graphics
      - Scripts

  - name: 'StarX Vanilla Vampires Revised.esp'
    url:
      - 'https://www.nexusmods.com/oblivion/mods/16417'
      - 'https://www.nexusmods.com/oblivion/mods/42912'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Has problems with OOO (StarX vampires will fight OOO vampires, and some chests/weapons will be in skewed places).'
          - lang: de
            text: 'Hat Probleme mit OOO (StarX Vampire werden mit OOO Vampiren kämpfen, und einige Truhen/Waffen werden in verstellten Orten sein).'
        condition: *OOOCond

  - name: 'UnnecessaryViolence.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/24936' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'If using with Supreme Magicka and experiencing frequent swirling pink or green clouds, set ''zzSMConfigurationQuest.bNoPoisonLevitationEffects'' to 1 in SupremeMagicka.ini.'
          - lang: de
            text: 'Wenn dies mit Supreme Magicka genutzt wird Sie erleben häufig wirbelnde pinke oder grüne Wolken, setzen Sie ''zzSMConfigurationQuest.bNoPoisonLevitationEffects'' auf 1 in der SupremeMagicka.ini.'
        condition: 'file("SupremeMagicka.esp")'

  - name: 'Vows and Covenants.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/20736' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Conflicts with Deadly Reflex. Minor Problems.'
          - lang: de
            text: 'Steht im Konflikt mit Deadly Reflex. Geringe Probleme.'
        condition: 'file("Deadly Reflex.*\.esp")'

  - name: 'Apachii_Goddess_Store.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/13437' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Recommended to enable only after you save game in IC Waterfront District'
          - lang: de
            text: 'Empfohlen dies erst zu aktivieren nachdem im IC Waterfront Abteil abgespeichert wurde'

  - name: 'Natural_Vegetation_by_Max_Tael.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Put before Unique Landscape mods to return tree sizes there to normal.'
          - lang: de
            text: 'Vor Unique Landscape Mods platzieren um Bäume zur normalen Größe zurück zu verändern.'
    dirty:
      - crc: 0xb02b5753
        <<: *dirtyPlugin
        itm: 1

  - name: 'Natural_Vegetation_200%_by_Max_Tael.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Put before Unique Landscape mods to return tree sizes there to normal.'
          - lang: de
            text: 'Vor Unique Landscape Mods platzieren um Bäume zur normalen Größe zurück zu verändern.'

  - name: 'Mage Equipment.esp'
    url:
      - 'https://www.nexusmods.com/oblivion/mods/13695'
      - 'https://www.nexusmods.com/oblivion/mods/18875'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Item sale prices will be excessive and unpredictable with OOO, FCOM and/or Living Economy'
          - lang: de
            text: 'Item Verkaufspreise werden überzogen und unvorhersehbar sein mit OOO, FCOM und/oder Living Economy'
      - type: say
        content:
          - lang: en
            text: 'If using Mage Equipment Lite, load after SRT.'
          - lang: de
            text: 'Wenn Mage Equipment Lite benutzt wird, dann nach SRT erst laden.'

  - name: 'Mage Equipment - No Manni.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/13695' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Item sale prices will be excessive and unpredictable with OOO, FCOM and/or Living Economy'
          - lang: de
            text: 'Item Verkaufspreise werden überzogen und unvorhersehbar sein mit OOO, FCOM und/oder Living Economy'
      - type: say
        content:
          - lang: en
            text: 'If using Mage Equipment Lite, load after SRT.'
          - lang: de
            text: 'Wenn Mage Equipment Lite benutzt wird, dann nach SRT erst laden.'

  - name: 'TolawaylAyleidCity_Quest.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/11526' ]
    msg:
      - type: warn
        content:
          - lang: en
            text: 'Deletes a door in the Cheydinhal Castle Private Quarters.'
          - lang: de
            text: 'Löscht eine Tür in Cheydinhal Castle Private Quarters.'

  - name: 'TheStorytellersBrotherQuest.esp'
    url:
      - 'https://www.nexusmods.com/oblivion/mods/3415'
      - 'https://www.nexusmods.com/oblivion/mods/7809'
    msg:
      - type: say
        content:
          - lang: en
            text: 'A fixed version can be found [here](http://www.nexusmods.com/oblivion/mods/7809).'
          - lang: de
            text: 'Eine fehlerfreie Version kann [hier](http://www.nexusmods.com/oblivion/mods/7809) abgerufen werden.'
```

</details>

**Comment by sibir-ine** [comment]
@Arthmoor, when looking at the commit history of BOSS's masterlist, I noticed that you added the current iteration of this message for `Cheydinhal Petshop.esp` in https://github.com/boss-developers/oblivion/commit/e2308aabf4f3e622592d9799b485b1da47e6231f:
> Has critical flaw affecting numerous mods. Remove immediately. Recommend replacing with Insanity's Pet Shop for same functionality.

The mod doesn't have posts enabled, I can't find anything about this via search engine, & nothing sets off any red flags after a cursory examination in xEdit. Do you happen to remember what the issue was? Is it to do with this bullet point from the readme:
> It is highly recommended that you only have one or two pets at a time; game limitations will cause script errors, game performance will decrease and cause instability.

Or is the issue always present? Also, [this](http://tesalliance.org/forums/index.php?/files/file/10-beta-insanitys-pet-shop/) is presumably the _Insanity's Pet Shop_ you were referring to?

**Comment by Arthmoor** [comment]
I don't remember the issue but I was able to dig up a couple of mentions, both from Emma.

http://lovkullen.net/Emma/Vilja.htm
https://emmates.proboards.com/post/36273/thread

Something about affecting a global time value in one of the scripts it has.

I suspect the details of what the exact problem is are lost to the ether on the old bethsoft forums.

**Comment by sibir-ine** [comment]
Thanks! That's enough detail as far as I'm concerned.

**Comment by MacSplody** [comment]
This one can be removed without replacing it.
```yaml
  - name: 'PMSneakySummons-ForVanilla.esp'
    msg:
      - type: say
        content:
          - lang: en
            text: 'To have magic overhaul features move before magic overhauls (but then you won''t get the features of this)'
          - lang: de
            text: 'Um Magie-Überhol Funktionalitäten zu haben, bewegen Sie es vor Magie-Überhol-Mods (aber dann bekommen Sie nicht die Funktionalitäten hiervon)'
```

---

Replace with use instead. [Insanitys Pet Shop](http://tesalliance.org/forums/index.php?/files/file/10-beta-insanitys-pet-shop/)
```yaml
  - name: 'Cheydinhal Petshop.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/2054' ]
    msg:
      - type: warn
        content:
          - lang: en
            text: 'Has critical flaw affecting numerous mods. Remove immediately. Recommend replacing with Insanity''s Pet Shop for same functionality.'
          - lang: de
            text: 'Hat kritischen Fehler die zahlreiche Mods betrifft. Umgehend zu Löschen. Empfohlen durch Insanity''s Pet Shop zu ersetzen für die selbe Funktionalität.'
```

Not sure if it's worth adding the cleaning data, since we're advising against using it.

```yaml
  - name: 'Cheydinhal Petshop.esp'
    dirty:
      - <<: *quickClean
        crc: 0xD5A4DC69
        util: '[TES4Edit v4.0.4b](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 8
        udr: 45
```
