### ISSUE TITLE
Better Letters - Cleaning Report (86 UDRs)

### ISSUE THREAD

**Issue by Sabre142** [loot/oblivion#397]
Mod name: Better Letters

Mod version: 1.3

Mod link: https://www.nexusmods.com/oblivion/mods/5392

Cleaning report:

```yaml
  - name: 'Cliff_BetterLetters.esp'
    dirty:
      - <<: *quickClean
        crc: 0x4E32A641
        util: '[TES4Edit v4.0.3h (Hotfix 1)](https://www.nexusmods.com/oblivion/mods/11536)'
        udr: 86
    clean:
      - crc: 0xEC01712C
        util: 'TES4Edit v4.0.3h (Hotfix 1)'
```

It also should be noted that version 1.3 of this mod no longer needs the Names bash tag, or any other bash tag for that matter (while version 1.2 did need it and Text).
