### ISSUE TITLE
ITM report

### ISSUE THREAD

**Issue by IllusiveMan196** [loot/oblivion#424]
- [x] [Competent Farmers](https://www.nexusmods.com/oblivion/mods/51310)
```
  - name: 'CompetentFarmers.esp'
    dirty:
      - <<: *quickClean
        crc: 0x08D5B154
        util: '[TES4Edit v4.0.3](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 45
        udr: 2
    clean:
      - crc: 0xF210BD2A
        util: 'TES4Edit v4.0.3
```
- [x] [Funny Loadscreens](https://www.nexusmods.com/oblivion/mods/19544)
```
  - name: 'toothman's funny loadscreens.esp'
    dirty:
      - <<: *quickClean
        crc: 0x22A419EE
        util: '[TES4Edit v4.0.3](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 2
    clean:
      - crc: 0x8672536A
        util: 'TES4Edit v4.0.3'
```
- [x] [Fuse Snail Racing](https://www.nexusmods.com/oblivion/mods/4596)
```
  - name: 'FuseSnailRacing.esp'
    dirty:
      - <<: *quickClean
        crc: 0x1157F5C1
        util: '[TES4Edit v4.0.3](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 16
        udr: 8
    clean:
      - crc: 0x86E8A5A4
        util: 'TES4Edit v4.0.3'
```
- [x] [Church Ruin Retreat (player home)](https://www.nexusmods.com/oblivion/mods/50738)
```
  - name: 'Church Ruin Retreat.esp'
    dirty:
      - <<: *quickClean
        crc: 0x4B7144F1
        util: '[TES4Edit v4.0.3](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 2
    clean:
      - crc: 0x026D341C
        util: 'TES4Edit v4.0.3'
```
- [x] [Curse of Hircine (main file)](https://www.nexusmods.com/oblivion/mods/35118)
```
  - name: 'CurseOfHircine.esp'
    dirty:
      - <<: *quickClean
        crc: 0x995AAE72
        util: '[TES4Edit v4.0.3](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 8
    clean:
      - crc: 0x069424A9
        util: 'TES4Edit v4.0.3'
```
- [x] [Mini Fixes (all fixes file)](https://www.nexusmods.com/oblivion/mods/13492)
```
  - name: 'mini fixes-all fixes.esp'
    dirty:
      - <<: *quickClean
        crc: 0x97D1DBE7
        util: '[TES4Edit v4.0.3](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 4
    clean:
      - crc: 0x9AB5906B
        util: 'TES4Edit v4.0.3'
```
