### ISSUE TITLE
Better Cities - Clocks of Cyrodiil replacer renamed

### ISSUE THREAD

**Issue by MacSplody** [loot/oblivion#44]
[Better Cities](https://www.nexusmods.com/oblivion/mods/16513)
[Clocks of Cyrodiil](https://www.nexusmods.com/oblivion/mods/11778)

[theassimilationlab.com - Better Cities version 6.0.0 changelog](http://www.theassimilationlab.com/forums/topic/15102-relz-better-cities/?do=findComment&comment=335656)

> Clocks of Cyrodiil replacer:
Removed compatibility for Open Cities Classic and Open Cities Reborn, as these mods are no longer modular, so it is not possible to use parts of OCC or OCR with parts of Better Cities.
Still compatible with Open Cities: Outer Districts.
_**File renamed to ClocksOfCyrodiil.esp**_

```yaml
  - name: 'ClocksOfCyrodiil.esp'
    msg:
      - type: say
        content: 'For use with Better Cities use ''ClocksOfCyrodiil_BC_OBC_OC_OCLR_Vanilla.esp'' instead.'
        condition: 'file("Better Cities Resources.esm")'
```
