### ISSUE TITLE
Hidden Treasures of Tamriel

### ISSUE THREAD

**Issue by Sabre142** [loot/oblivion#443]
Mod name: Hidden Treasures of Tamriel

Mod version: 1.1

Mod link: https://www.nexusmods.com/oblivion/mods/45980

Optimal loading order: I actually recommend loading this mod BEFORE the Unofficial Patches. I say this because it will undo some of the fixes in the Unofficial Shivering Isles Patch that cannot be imported by any bash tags. Namely, the music type in Bliss, Crucible and Palace Grounds will be different. You can open the mods in TES4Edit to see that conflict.

![image](https://user-images.githubusercontent.com/26516348/133160994-bee737cd-939e-4638-99d5-e86760a30854.png)

![image](https://user-images.githubusercontent.com/26516348/133161016-75ba5c5d-c5ab-4300-938f-e91c08ef0ed1.png)

Cleaning report:

```yaml
  - name: 'Hidden Treasures.esp'
    dirty:
      - <<: *quickClean
        crc: 0x921AA706
        util: '[TES4Edit v4.0.3h (Hotfix 1)](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 1
    clean:
      - crc: 0x40CC52E5
        util: 'TES4Edit v4.0.3h (Hotfix 1)'
```

No bash tags are needed.

**Comment by MacSplody** [comment]
It's is only adding new content, so I can't see the harm in placing it early.
![image](https://user-images.githubusercontent.com/1944639/133164895-fe310163-7e0c-472c-90dd-4eadabc02c94.png)

Metadata below should work.

```yaml
  - name: 'Hidden Treasures.esp'
    group: 'Very Early Loaders'
    req: [ 'DLCShiveringIsles.esp' ]

  - name: 'Unofficial Shivering Isles Patch.esp'
    after:
      - 'Hidden Treasures.esp'
```
