### ISSUE TITLE
Black Horse Courier Expanded - Incorrect plugin name used

### ISSUE THREAD

**Issue by MacSplody** [loot/oblivion#49]
[Black Horse Courier Expanded](https://www.nexusmods.com/oblivion/mods/27029)

```yaml
  - name: 'BHC_Expanded.esp'
    dirty:
      - crc: 0xc73a3567
        <<: *dirtyPlugin
        itm: 2
        udr: 12
      - crc: 0xdf5b8901
        <<: *dirtyPlugin
        itm: 2
        udr: 12
```
Added in https://github.com/loot/oblivion/commit/cedf384d48ed41507572af14800339672768f332
```yaml
  - name: 'BlackHorseCourierExpanded.esp'
    dirty:
      # Version: 1.2
      - <<: *quickClean
        crc: 0xC73A3567
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 2
        udr: 12
    clean:
      # Version: 1.2
      - crc: 0x47CE6324
        util: 'TES4Edit v4.0.2'
```
