### ISSUE TITLE
Daedric Shrines Prodded With A Stick

### ISSUE THREAD

**Issue by Sabre142** [loot/oblivion#500]
Mod name: Daedric Shrines Prodded With A Stick

Mod version: 2.0

Mod link: https://www.nexusmods.com/oblivion/mods/46930/

Cleaning report:

```yaml
  - name: 'DaedraShrinesProddedWithAStick.esp'
    dirty:
      - <<: *quickClean
        crc: 0x417B6DEB
        util: '[TES4Edit v4.0.3h (Hotfix 1)](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 8
    clean:
      - crc: 0x48823304
        util: 'TES4Edit v4.0.3h (Hotfix 1)'
```

```yaml
  - name: 'KOTNPokedWithAStick.esp'
    clean:
      - crc: 0x7F19A6E5
        util: 'TES4Edit v4.0.3h (Hotfix 1)'
```

Suggested bash tags for DaedraShrinesProddedWithAStick.esp:

```
      - Actors.AIPackages
      - Actors.Spells
      - Invent.Add
```

Suggested bash tags for KOTNPokedWithAStick.esp:

```
      - Actors.AIPackages
      - Factions
```
