### ISSUE TITLE
TES4Edit Cleaning Reports

### ISSUE THREAD

**Issue by MacSplody** [loot/oblivion#51]
Submit Quick Auto Cleaning Reports as a comment below.
Make sure you **link** the mod page and specify the mod **version** you cleaned as well.

[Quick Auto Clean](https://tes5edit.github.io/docs/5-mod-cleaning-and-error-checking.html#quickautoclean)
[Add arguments](https://user-images.githubusercontent.com/1944639/48548367-b2744b00-e8c4-11e8-8a75-a0b67a4d7ed8.png)
`-iknowwhatimdoing -quickautoclean` in MO2

[Copy the Quick Auto Clean report](https://user-images.githubusercontent.com/1944639/48547682-1eee4a80-e8c3-11e8-8e2b-fd0b571f71fc.png)

It's preferable to wrap this in a comment for readability.
![image](https://user-images.githubusercontent.com/1944639/48547617-fb2b0480-e8c2-11e8-969d-f7b698b05e05.png)

```yaml
  - name: 'Knights.esp'
    dirty:
      - <<: *quickClean
        crc: 0xF1F478FA
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 117
        udr: 255
    clean:
      - crc: 0x044A414D
        util: 'TES4Edit v4.0.2'
```
---

**Comment by MacSplody** [comment]
[Francescos Creatures and Items - V5](https://www.nexusmods.com/oblivion/mods/40190)

```yaml
  - name: 'Francesco''s Leveled Creatures-Items Mod.esm'
    clean:
      # version: 5.0B1 No Extras
      - crc: 0x6E140E64
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 Combat Tweaks
      - crc: 0xA202CFEE
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 MOBS
      - crc: 0x86F701A8
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 MOBS + Combat Tweaks
      - crc: 0xA6E20DD9
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 SI
      - crc: 0x40DB6674
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 SI + Combat Tweaks
      - crc: 0x1C4954F9
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 SI MOBS
      - crc: 0xFC291261
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 SI MOBS + Combat Tweaks
      - crc: 0x4CC0CFD7
        util: 'TES4Edit v4.0.2'

  - name: 'Francesco''s Optional New Items Add-On.esm'
    clean:
      # version: 5.0B1
      - crc: 0x2F92934E
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 MOBS
      - crc: 0x4EC479E6
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 SI
      - crc: 0x36E8215E
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 SI + MOBS
      - crc: 0x754C4DFF
        util: 'TES4Edit v4.0.2'

  - name: 'Francesco''s Optional New Creatures Add-On.esm'
    dirty:
      # version: 5.0B1 No Extras
      - <<: *quickClean
        crc: 0x05C1179C
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 2
      # version: 5.0B1 Higher Spawn Chance
      - <<: *quickClean
        crc: 0x7E6C2002
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 2
      # version: 5.0B1 SI
      - <<: *quickClean
        crc: 0xEC1ED965
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 2
      # version: 5.0B1 SI + Higher Spawn Chance
      - <<: *quickClean
        crc: 0x7954ED0D
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 2
    clean:
      # version: 5.0B1 No Extras, after QAC
      - crc: 0x9472C1EF
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 Higher Spawn Chance, after QAC
      - crc: 0x4FF3B5BD
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 SI, after QAC
      - crc: 0xED3C342E
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 SI + Higher Spawn Chance, after QAC
      - crc: 0xD09310C3
        util: 'TES4Edit v4.0.2'

  - name: 'Francesco''s More Wilderness Life.esp'
    dirty:
      # version: 5.0B1
      - <<: *quickClean
        crc: 0x60471138
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 13
      # version: 5.0B1 Hardcore
      - <<: *quickClean
        crc: 0xB5D7D5D3
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 13
      # version: 5.0B1 Extra Hardcore
      - <<: *quickClean
        crc: 0x9AAFAB5D
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 13
    clean:
      # version: 5.0B1, after QAC
      - crc: 0xE4D78C60
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 Hardcore, after QAC
      - crc: 0x7368D226
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 Extra Hardcore, after QAC
      - crc: 0x20558609
        util: 'TES4Edit v4.0.2'

  - name: 'Francesco''s Optional Chance of More Enemies.esp'
    clean:
      # version: 5.0B1
      - crc: 0x834225AC
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 Hardcore
      - crc: 0x723E4920
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 Extra Hardcore
      - crc: 0x8CA49385
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 SI
      - crc: 0xE02591A7
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 SI Hardcore
      - crc: 0x248C8931
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 SI Extra Hardcore
      - crc: 0x2FF407FF
        util: 'TES4Edit v4.0.2'

  - name: 'Francesco''s Optional Chance of Stronger Bosses.esp'
    clean:
      # version: 5.0B1
      - crc: 0xC4F8B2FA
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 SI
      - crc: 0x19C52F4F
        util: 'TES4Edit v4.0.2'

  - name: 'Francesco''s Optional Chance of Stronger Enemies.esp'
    clean:
      # version: 5.0B1
      - crc: 0x08F1B16D
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 SI
      - crc: 0x69CDAE26
        util: 'TES4Edit v4.0.2'

  - name: 'Francesco''s Optional Dungeon Chest Locks.esp'
    dirty:
      # version: 5.0B1
      - <<: *quickClean
        crc: 0xE6986FB8
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 2
      # version: 5.0B1 SI
      - <<: *quickClean
        crc: 0xE8D24A94
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 2
    clean:
      # version: 5.0B1, after QAC
      - crc: 0xFD07463F
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 SI, after QAC
      - crc: 0x417EB6BA
        util: 'TES4Edit v4.0.2'

  - name: 'Francesco''s Optional Dungeon Chest Loot.esp'
    dirty:
      # version: 5.0B1
      - <<: *quickClean
        crc: 0xA8DDDA6F
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 2
      # version: 5.0B1 SI
      - <<: *quickClean
        crc: 0x94B735A6
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 2
    clean:
      # version: 5.0B1, after QAC
      - crc: 0x68F92434
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 SI, after QAC
      - crc: 0x5CBC5748
        util: 'TES4Edit v4.0.2'

  - name: 'Francesco''s Optional House Chest Loot.esp'
    clean:
      # version: 5.0B1
      - crc: 0x968F569D
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 SI
      - crc: 0x968F569D
        util: 'TES4Edit v4.0.2'

  - name: 'Francesco''s Optional Leveled Arena.esp'
    clean:
      # version: 5.0B1
      - crc: 0xB3A72219
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 SI
      - crc: 0xB3A72219
        util: 'TES4Edit v4.0.2'

  - name: 'Francesco''s Optional Leveled Guards.esp'
    clean:
      # version: 5.0B1
      - crc: 0xF336E22D
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 SI
      - crc: 0x4B2B4B48
        util: 'TES4Edit v4.0.2'

  - name: 'Francesco''s Optional Leveled Quests.esp'
    dirty:
      # version: 5.0B1
      - <<: *quickClean
        crc: 0x6876A2AA
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 1
        udr: 311
      # version: 5.0B1 SI
      - <<: *quickClean
        crc: 0xAA79DA0D
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 3
        udr: 311
    clean:
      # version: 5.0B1, after QAC
      - crc: 0x27188AD5
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 SI, after QAC
      - crc: 0x89CD3F95
        util: 'TES4Edit v4.0.2'

  - name: 'Francesco''s Optional New Adventurers.esp'
    clean:
      # version: 5.0B1
      - crc: 0xCBA1CE61
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 SI
      - crc: 0xCBA1CE61
        util: 'TES4Edit v4.0.2'

  - name: 'Francesco''s Optional Vendor Tweaks.esp'
    clean:
      # version: 5.0B1
      - crc: 0x506AFA75
        util: 'TES4Edit v4.0.2'
      # version: 5.0B1 SI
      - crc: 0x506AFA75
        util: 'TES4Edit v4.0.2'
```

**Comment by MacSplody** [comment]
[Common Oblivion (Cobl)](https://www.nexusmods.com/oblivion/mods/21104)
version: 1.72

_Core Modules_
```yaml
  - name: 'Cobl Main.esm'
    clean:
      - crc: 0x8284D0E6
        util: 'TES4Edit v4.0.2'
  - name: 'Cobl Glue.esp'
    dirty:
      - <<: *quickClean
        crc: 0xEAB6315A
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        udr: 14
    clean:
      - crc: 0x1DBAD1A7
        util: 'TES4Edit v4.0.2'
  - name: 'Cobl Tweaks.esp'
    clean:
      - crc: 0x905EBDCE
        util: 'TES4Edit v4.0.2'
  - name: 'Cobl Si.esp'
    clean:
      - crc: 0xF7ADF908
        util: 'TES4Edit v4.0.2'
  - name: 'Cobl Races.esp'
    clean:
      - crc: 0xAA29DCA8
        util: 'TES4Edit v4.0.2'
```
_Balanced Races_
```yaml
  - name: 'Cobl Races - Balanced.esp'
    clean:
      - crc: 0x8C1A854E
        util: 'TES4Edit v4.0.2'
```
_Salmo the Baker, Cobl_
```yaml
  - name: 'Salmo the Baker, Cobl.esp'
    dirty:
      - <<: *quickClean
        crc: 0xE02E250D
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 36
    clean:
      - crc: 0x85042A99
        util: 'TES4Edit v4.0.2'
```

_Cobl Races TNR_ (Tamriel NPCs Revamped)
```yaml
  - name: 'Cobl Races TNR.esp'
    clean:
      - crc: 0xEE36BE6B
        util: 'TES4Edit v4.0.2'
  - name: 'Cobl Races TNR SI.esp'
    clean:
      - crc: 0x1BF099CF
        util: 'TES4Edit v4.0.2'
```

_Patches_
```yaml
  - name: 'Cobl Silent Equip Misc.esp'
    clean:
      - crc: 0x5860AF9A
        util: 'TES4Edit v4.0.2'
  - name: 'MMM-Cobl.esp'
    clean:
      - crc: 0x82EE4E0B
        util: 'TES4Edit v4.0.2'
  - name: 'OOO 1.32-Cobl.esp'
    clean:
      - crc: 0x23312D99
        util: 'TES4Edit v4.0.2'
```

[_Item interchange_](https://www.nexusmods.com/oblivion/mods/17557)
Old version 0.76, current is v88b
```yaml
  - name: 'Item interchange - Placement for Frostcrag.esp'
    clean:
      - crc: 0x1076BEF1
        util: 'TES4Edit v4.0.2'
  - name: 'Item interchange - Placement for Frostcrag Reborn.esp'
    clean:
      - crc: 0x3D0ED118
        util: 'TES4Edit v4.0.2'
  - name: 'Item interchange - Placement for Frostcrag Spire Revisited.esp'
    clean:
      - crc: 0x86350BF7
        util: 'TES4Edit v4.0.2'
```
_Modders Only_
```yaml
  - name: 'Cobl Mort Demo.esp'
    clean:
      - crc: 0x8A8B7C71
        util: 'TES4Edit v4.0.2'
```

**Comment by MacSplody** [comment]
### Martigen’s Monster Mod
https://www.nexusmods.com/oblivion/mods/17784
http://tesalliance.org/forums/index.php?/files/file/1965-martigens-monster-mod-38/
version: 3.8

```yaml
  - name: 'Mart's Monster Mod.esm'
    dirty:
      - <<: *quickClean
        crc: 0xFA08DE55
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 1
    clean:
      - crc: 0xC1590EE4
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod for OOO.esm'
    dirty:
      - <<: *quickClean
        crc: 0x435C16D9
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 3
    clean:
      - crc: 0x3EFCF6A5
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Shivering Isles.esp'
    dirty:
      - <<: *quickClean
        crc: 0xDF4B7C20
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 3
    clean:
      - crc: 0x7609EC8B
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Knights.esp'
    dirty:
      - <<: *quickClean
        crc: 0x51DBA3E6
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 2
    clean:
      - crc: 0x04AC1E1C
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod.esp'
    dirty:
      - <<: *quickClean
        crc: 0x8528FB34
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 904
    clean:
      - crc: 0x658B5449
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod for Fran.esp'
    dirty:
      - <<: *quickClean
        crc: 0x4D843B1C
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 870
    clean:
      - crc: 0xA5A90B59
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod for OOO.esp'
    dirty:
      - <<: *quickClean
        crc: 0x33A4E76A
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 402
    clean:
      - crc: 0x14B2A180
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Additional Enemy NPC Vars.esp'
    dirty:
      - <<: *quickClean
        crc: 0xF02F3B04
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 3
    clean:
      - crc: 0xA7BB1006
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - City Defences.esp'
    dirty:
      - <<: *quickClean
        crc: 0x758B61E2
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 1
    clean:
      - crc: 0x033C138B
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Curse of Hircine.esp'
    clean:
      - crc: 0xBD0F4261
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Diverse Creatures Expansion.esp'
    clean:
      - crc: 0xE300B724
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Diverse Imperial Armor.esp'
    dirty:
      - <<: *quickClean
        crc: 0x2A650097
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 2
    clean:
      - crc: 0x95208CDE
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Diverse Runeskulls Loot.esp'
    clean:
      - crc: 0xF8F36924
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Diverse Runeskulls Loot G&GD.esp'
    clean:
      - crc: 0xBC851604
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Diverse Runeskulls Loot OOO.esp'
    clean:
      - crc: 0x932A57C9
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Diverse WaterLife.esp'
    clean:
      - crc: 0x75A8F813
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Divserse Wisp and VASE Addon.esp'
    clean:
      - crc: 0xE79AC594
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - DLCHorseArmor+Slofs .esp'
    clean:
      - crc: 0xDEB6DE93
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Dungeons of MMM.esp'
    clean:
      - crc: 0x9208A5D0
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Durability & Damage.esp'
    clean:
      - crc: 0xA9481543
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Extra Wounding.esp'
    dirty:
      - <<: *quickClean
        crc: 0xD8C0168F
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 2
    clean:
      - crc: 0x1EFF4DD0
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Farm Animals.esp'
    clean:
      - crc: 0x7AD3E3A9
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Friendlier Factions MMM+Fran.esp'
    clean:
      - crc: 0x5794FAE2
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Fran's leveled quests.esp'
    clean:
      - crc: 0xDE377299
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Friendlier Factions OOO.esp'
    dirty:
      - <<: *quickClean
        crc: 0x2E446319
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 2
    clean:
      - crc: 0xDA7CC4E3
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Gems & Gem Dust.esp'
    clean:
      - crc: 0x5327F263
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Hemingwey Capes Addon.esp'
    dirty:
      - <<: *quickClean
        crc: 0x497A32B5
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 106
    clean:
      - crc: 0xF8F6AF64
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Hemingweys NPC Capes Improved.esp'
    dirty:
      - <<: *quickClean
        crc: 0x56442922
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 10
    clean:
      - crc: 0x5BACD890
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Hunting & Crafting.esp'
    clean:
      - crc: 0xD53A8A19
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Less Bone Loot.esp'
    clean:
      - crc: 0xA78B9CE3
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Less Rats.esp'
    clean:
      - crc: 0xED551EA9
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Less Reavers.esp'
    clean:
      - crc: 0xCC3F03C7
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Looting NPCs & Creatures.esp'
    clean:
      - crc: 0x0674FBEA
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - More Passive Wildlife.esp'
    clean:
      - crc: 0xBDFC5F0E
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - More Wilderness Life.esp'
    dirty:
      - <<: *quickClean
        crc: 0xFEA2D531
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 18
    clean:
      - crc: 0x9A239CBF
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - More Wilderness Life No Gates.esp'
    dirty:
      - <<: *quickClean
        crc: 0xA6DAAFD5
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 22
    clean:
      - crc: 0xD353A734
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - No Adventurers.esp'
    clean:
      - crc: 0x848043F2
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - No Balrogs.esp'
    clean:
      - crc: 0x38D2B986
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - No Beholdens.esp'
    clean:
      - crc: 0xC6C70215
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - No Blood.esp'
    clean:
      - crc: 0xB1108D5F
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - No Bone Loot.esp'
    clean:
      - crc: 0x6EB28406
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - No Carrion Rats.esp'
    clean:
      - crc: 0xEEE80176
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - No Fiends.esp'
    clean:
      - crc: 0x7CD34790
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - No Ghostly Appariation.esp'
    clean:
      - crc: 0x36D4B02D
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - No Giants.esp'
    clean:
      - crc: 0xC3D39B1E
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - No Lanterns.esp'
    clean:
      - crc: 0xB4AF9751
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - No Pests.esp'
    clean:
      - crc: 0xFD5158B2
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - No Reavers.esp'
    clean:
      - crc: 0x36A744E9
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - No Skeep.esp'
    clean:
      - crc: 0x4EDBFE3F
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - No Slimes.esp'
    clean:
      - crc: 0xADAEDF08
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - No Spiders.esp'
    clean:
      - crc: 0x489071F2
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - No Swarms.esp'
    clean:
      - crc: 0x31E5E710
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - No Uberhulks.esp'
    clean:
      - crc: 0xBF1E308C
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - No Undead Rise.esp'
    dirty:
      - <<: *quickClean
        crc: 0x1E8FCF0B
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 1
    clean:
      - crc: 0xB91735D7
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - No Werewolves.esp'
    clean:
      - crc: 0xB069AB27
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - No Wyvern.esp'
    clean:
      - crc: 0x47EF9F9E
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod for OOO - Knights .esp'
    dirty:
      - <<: *quickClean
        crc: 0x436D9B8D
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 2
    clean:
      - crc: 0x87258C0D
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod for OOO - LessReaversInGates.esp'
    clean:
      - crc: 0xFCA5FBC1
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod for OOO - NoReaversInGates.esp'
    clean:
      - crc: 0xB18E484D
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - RadiantAITweaks.esp'
    clean:
      - crc: 0x801334B7
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Resized Races.esp'
    clean:
      - crc: 0xE29818CA
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Safer Quest Locations.esp'
    clean:
      - crc: 0xEE8175FD
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Safer Roads.esp'
    clean:
      - crc: 0xC1316241
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Slof Horses Complete.esp'
    clean:
      - crc: 0x4618F324
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Spawn Rates - Increased.esp'
    dirty:
      - <<: *quickClean
        crc: 0x16438018
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 1
    clean:
      - crc: 0xAFCC8590
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Spawn Rates - Moderate Increased.esp'
    clean:
      - crc: 0xA63575E0
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Spawn Rates - Reduced.esp'
    clean:
      - crc: 0xC6BB0E58
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Spawn Rates - Reduced Reduced.esp'
    clean:
      - crc: 0xF9D8C6D8
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Spawn Rates - Reduced Vanilla.esp'
    clean:
      - crc: 0x3EE2CD43
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Undead Rise Fix.esp'
    dirty:
      - <<: *quickClean
        crc: 0xE037E256
        util: '[TES4Edit v4.0.2](https://www.nexusmods.com/oblivion/mods/11536)'
        itm: 12
    clean:
      - crc: 0x8D76C7D9
        util: 'TES4Edit v4.0.2'

  - name: 'Mart's Monster Mod - Zombies for Body Meshes.esp'
    clean:
      - crc: 0x6C98F68D
        util: 'TES4Edit v4.0.2'
```
