### ISSUE TITLE
SM Plugin Refurbish Lite.esp needs Actors.RecordFlags bash tag

### ISSUE THREAD

**Issue by Sabre142** [loot/oblivion#539]
Mod link: https://www.nexusmods.com/oblivion/mods/11474

Mod version: 2.1

```yaml
  - name: 'SM Plugin Refurbish Lite.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/11474' ]
    tag: [ Actors.RecordFlags ]
```

Modifies 3 NPC records and their record flags:

![image](https://user-images.githubusercontent.com/26516348/137691087-50132e75-66de-4b87-9dca-7e1380ecb993.png)
