### ISSUE TITLE
Add check to travis for duplicate iso codes in Localised Content

### ISSUE THREAD

**Issue by MacSplody** [loot/oblivion#61]
As contributors that copy and paste an existing list item might forget to update the iso code.
Reviewers could also miss the duplcate.

Currently the below change will build in travis.
I'm not sure how LOOT would display this, would it show both or the last value?

```yaml
  - &corrupt
    type: warn
    content:
      - lang: en
        text: 'This file is corrupt and should not be used.'
      - lang: ru
        text: 'Файл испорчен и не должен использоваться.'
      - lang: es
        text: 'Este archivo puede corromper tu juego y no debería ser utilizado.'
      - lang: ja
        text: 'このファイルは壊れています。使用しないでください。'
      - lang: pt_BR
        text: 'Este arquivo está corrompido e não deveria ser utilizado.'
      - lang: pt_BR
        text: 'Ten plik jest zepsuty i nie powinien być używany.'
```
